casos_tribunal = [{'pregunta': '¿Usar filtros que cambian completamente tu cara es engañar a los demás?',
  'opciones': ['Sí, es publicidad engañosa',
               'No, cada uno publica lo que quiere',
               'Solo si nunca enseña su aspecto real',
               'Depende de cuánto cambie']},
 {'pregunta': '¿Te acostarías con alguien que no te atrae físicamente si existe mucha conexión personal?',
  'opciones': ['Sí, la conexión pesa más',
               'No, necesito atracción física',
               'Depende del momento',
               'Lo he hecho y no repetiría']},
 {'pregunta': '¿Se puede querer de verdad a dos personas al mismo tiempo?',
  'opciones': ['Sí, perfectamente',
               'No, una de las dos no es amor',
               'Puede pasar, pero hay que elegir',
               'Depende del tipo de relación']},
 {'pregunta': '¿Perdonarías una infidelidad si solo hubiera ocurrido una vez?',
  'opciones': ['Sí, si existe arrepentimiento',
               'No, jamás',
               'Dependería de las circunstancias',
               'Perdonaría, pero no seguiría']},
 {'pregunta': 'Tu mejor amigo te confiesa que ha sido infiel. ¿Se lo contarías a su pareja?',
  'opciones': ['Sí, merece saberlo',
               'No, no es asunto mío',
               'Le obligaría a contarlo él',
               'Dependería de quién sea su pareja']},
 {'pregunta': '¿Es peor una mentira directa o esconder información importante?',
  'opciones': ['La mentira directa',
               'Ocultar información',
               'Las dos son igual de graves',
               'Depende de la intención']},
 {'pregunta': '¿Dejar a alguien por mensaje puede estar justificado?',
  'opciones': ['Sí, en algunas situaciones',
               'No, siempre debe ser en persona',
               'Solo si la relación era breve',
               'Depende de cómo se comporte la otra persona']},
 {'pregunta': '¿El físico importa más de lo que la mayoría reconoce?',
  'opciones': ['Sí, muchísimo',
               'No, la personalidad manda',
               'Importa al principio, después menos',
               'Depende de cada persona']},
 {'pregunta': '¿Revisarías el móvil de tu pareja si tuvieras sospechas muy fundadas?',
  'opciones': ['Sí, necesito saber la verdad',
               'No, sería cruzar una línea',
               'Primero hablaría con esa persona',
               'Depende de lo que hubiera ocurrido']},
 {'pregunta': '¿Crees que alguien que ha sido infiel una vez probablemente volverá a serlo?',
  'opciones': ['Sí, quien lo hace repite',
               'No, la gente puede cambiar',
               'Depende de por qué ocurrió',
               'No se puede generalizar']},
 {'pregunta': '¿Ghostear puede estar justificado cuando alguien no acepta un rechazo?',
  'opciones': ['Sí, totalmente',
               'No, siempre hay que explicarse',
               'Solo después de haberlo hablado',
               'Bloqueo directo y a otra cosa']},
 {'pregunta': '¿Aceptarías dinero a cambio de fingir una relación durante un mes?',
  'opciones': ['Sí, sin problema',
               'No, ni de broma',
               'Depende de cuánto dinero',
               'Solo si nadie sale perjudicado']},
 {'pregunta': '¿Es correcto cancelar una cita porque ha aparecido un plan que te apetece más?',
  'opciones': ['Sí, cada uno elige su tiempo',
               'No, es una falta de respeto',
               'Solo avisando con suficiente tiempo',
               'Depende de la confianza']},
 {'pregunta': '¿Una persona puede parecerte menos atractiva después de conocer su personalidad?',
  'opciones': ['Sí, completamente',
               'No, el físico no cambia',
               'Puede ganar o perder mucho',
               'Depende de lo grave que descubras']},
 {'pregunta': '¿Deberías avisar a alguien si sabes que su pareja le está engañando, aunque apenas lo '
              'conozcas?',
  'opciones': ['Sí, tiene derecho a saberlo',
               'No, no me metería',
               'Solo si tengo pruebas',
               'Se lo diría de forma anónima']},
 {'pregunta': '¿Subir fotos buscando aprobación es inseguridad o simple entretenimiento?',
  'opciones': ['Principalmente inseguridad',
               'Simple entretenimiento',
               'Todos buscamos aprobación en parte',
               'Depende de la frecuencia']},
 {'pregunta': '¿Aceptarías una amistad con alguien que sabes que está enamorado de ti?',
  'opciones': ['Sí, si respeta los límites',
               'No, sería hacerle daño',
               'Solo si sus sentimientos disminuyen',
               'Dependería de nuestra historia']},
 {'pregunta': '¿Volverías con una expareja si te demostrara que ha cambiado?',
  'opciones': ['Sí, daría otra oportunidad',
               'No, lo pasado queda atrás',
               'Depende del motivo de la ruptura',
               'Solo si ha pasado mucho tiempo']},
 {'pregunta': '¿Es posible ser amigo de un ex sin que quede ningún sentimiento?',
  'opciones': ['Sí, perfectamente',
               'No, siempre queda algo',
               'Solo después de mucho tiempo',
               'Depende de cómo terminó']},
 {'pregunta': '¿Mentirías sobre dónde estás para evitar una discusión innecesaria?',
  'opciones': ['Sí, por tranquilidad',
               'No, nunca',
               'Lo omitiría, pero no mentiría',
               'Depende de la relación']},
 {'pregunta': '¿Es egoísta tener hijos sabiendo que no puedes ofrecerles estabilidad económica?',
  'opciones': ['Sí, hay que ser responsable',
               'No, el amor es lo esencial',
               'Depende del nivel de dificultad',
               'Nadie tiene estabilidad garantizada']},
 {'pregunta': '¿Aceptarías que tu pareja mantuviera una amistad muy cercana con su ex?',
  'opciones': ['Sí, si existe confianza',
               'No, me incomodaría demasiado',
               'Solo con límites claros',
               'Dependería de cómo terminaron']},
 {'pregunta': '¿Bloquear a alguien sin darle explicaciones es inmaduro?',
  'opciones': ['Sí, siempre',
               'No, nadie debe explicaciones',
               'Depende de lo que haya hecho',
               'A veces es la opción más sana']},
 {'pregunta': '¿Es correcto seguir hablando con alguien que tiene pareja si notas que existe tensión entre '
              'ambos?',
  'opciones': ['Sí, mientras no ocurra nada',
               'No, hay que alejarse',
               'La responsabilidad es de quien tiene pareja',
               'Depende de la intención']},
 {'pregunta': '¿Preferirías una verdad dolorosa o vivir tranquilo sin conocerla?',
  'opciones': ['Siempre la verdad',
               'Prefiero no saberlo',
               'Depende de lo que cambie',
               'Solo la verdad si puedo actuar']},
 {'pregunta': '¿La gente cambia de verdad o solo aprende a ocultar mejor sus defectos?',
  'opciones': ['La gente sí cambia',
               'Solo aprende a disimular',
               'Cambia si realmente quiere',
               'Algunas cosas nunca cambian']},
 {'pregunta': "¿Te parecería mal que tu pareja diera 'me gusta' constantemente a fotos provocativas?",
  'opciones': ['Sí, es una falta de respeto',
               'No, solo son redes sociales',
               'Me incomodaría, pero lo hablaría',
               'Depende de quién publique la foto']},
 {'pregunta': '¿Una persona debe contar desde el principio todos sus errores del pasado?',
  'opciones': ['Sí, para empezar con sinceridad',
               'No, el pasado es privado',
               'Solo lo que pueda afectar a la relación',
               'Debe contarlo cuando exista confianza']},
 {'pregunta': '¿Saldrías con alguien que no gusta nada a tus amigos?',
  'opciones': ['Sí, es mi decisión',
               'No, suelen ver cosas que yo no',
               'Escucharía sus razones',
               'Depende de cuántos coincidan']},
 {'pregunta': '¿Es correcto mantener contacto con alguien únicamente porque te gusta la atención que te da?',
  'opciones': ['No, es utilizar a la persona',
               'Sí, si ambos lo saben',
               'Todos lo hacemos alguna vez',
               'Depende de si se crean falsas expectativas']},
 {'pregunta': '¿Dar celos a propósito es una forma de manipulación?',
  'opciones': ['Sí, claramente',
               'No, es solo provocación',
               'Depende de la intención',
               'Solo si se hace repetidamente']},
 {'pregunta': '¿Dejarías una amistad porque tu pareja se siente incómoda con esa persona?',
  'opciones': ['Sí, priorizaría la relación',
               'No, nadie decide mis amistades',
               'Intentaría llegar a un acuerdo',
               'Depende del motivo']},
 {'pregunta': '¿Te molestaría que alguien tardara horas en responder mientras publica historias?',
  'opciones': ['Sí, demuestra desinterés',
               'No, puede estar ocupado',
               'Solo si ocurre siempre',
               'Depende de la relación']},
 {'pregunta': '¿Es justo exigir exclusividad antes de haber hablado claramente de exclusividad?',
  'opciones': ['Sí, si hay conexión evidente',
               'No, hay que hablarlo',
               'Depende del tiempo',
               'Nunca debe asumirse']},
 {'pregunta': '¿Ocultar una conversación porque sabes que molestaría es ya una traición?',
  'opciones': ['Sí', 'No, todos tenemos privacidad', 'Depende del contenido', 'Es una señal de alarma']},
 {'pregunta': '¿Aceptarías una relación en la que nunca se publicara nada juntos en redes?',
  'opciones': ['Sí, las redes no importan',
               'No, parecería ocultamiento',
               'Solo si es coherente',
               'Depende del tiempo']},
 {'pregunta': '¿Una persona que coquetea con todo el mundo puede ser completamente fiel?',
  'opciones': ['Sí', 'No', 'Depende de los límites', 'Puede ser fiel, pero agotadora']},
 {'pregunta': '¿Se puede considerar infidelidad hablar sexualmente con alguien sin llegar a verse?',
  'opciones': ['Sí',
               'No, sin contacto físico no',
               'Depende de los acuerdos',
               'Es traición aunque no sea física']},
 {'pregunta': '¿Aceptarías salir con alguien que sigue viviendo con su ex por motivos económicos?',
  'opciones': ['Sí, con límites claros',
               'No, demasiado complicado',
               'Depende de la situación',
               'Solo con transparencia total']},
 {'pregunta': '¿La sinceridad absoluta puede ser cruel e innecesaria?',
  'opciones': ['Sí, no todo debe decirse',
               'No, la verdad siempre',
               'Depende de la intención',
               'Hay formas y momentos']},
 {'pregunta': '¿Es correcto investigar a alguien en redes antes de una cita?',
  'opciones': ['Sí, por seguridad', 'No, condiciona demasiado', 'Solo lo básico', 'Todos lo hacemos']},
 {'pregunta': '¿Se puede reconstruir la confianza al cien por cien después de una traición?',
  'opciones': ['Sí',
               'No, siempre queda una grieta',
               'Puede mejorar, pero no ser igual',
               'Depende de la traición']},
 {'pregunta': '¿Es egoísta seguir en una relación por miedo a estar solo?',
  'opciones': ['Sí', 'No, es humano', 'Depende de si intentas arreglarla', 'Es más miedo que egoísmo']},
 {'pregunta': '¿Una relación sin discusiones es sana o sospechosa?',
  'opciones': ['Sana', 'Sospechosa', 'Depende de cómo comuniquen', 'No discutir no es no tener conflictos']},
 {'pregunta': '¿Te parecería mal que tu pareja hablara de vuestros problemas con sus amistades?',
  'opciones': ['Sí, es privado',
               'No, necesita desahogarse',
               'Solo sin detalles íntimos',
               'Depende de con quién']},
 {'pregunta': '¿Dar una segunda oportunidad obliga a dejar de sacar el tema?',
  'opciones': ['Sí, si decides perdonar',
               'No, sanar lleva tiempo',
               'Depende de cómo se hable',
               'Perdonar no es olvidar']},
 {'pregunta': '¿Te irías de una cita si la otra persona trata mal al personal?',
  'opciones': ['Sí, inmediatamente',
               'No, terminaría y luego nada más',
               'Le llamaría la atención',
               'Depende de lo ocurrido']},
 {'pregunta': '¿Es correcto pedir ubicación en tiempo real a una pareja?',
  'opciones': ['Sí, por seguridad',
               'No, es control',
               'Solo en ocasiones concretas',
               'Depende de si ambos quieren']},
 {'pregunta': '¿Las contraseñas de pareja son confianza o invasión?',
  'opciones': ['Confianza', 'Invasión', 'Depende de si es voluntario', 'No deberían necesitarse']},
 {'pregunta': '¿Te parece red flag que alguien no tenga amistades cercanas?',
  'opciones': ['Sí', 'No, puede tener motivos', 'Depende de su historia', 'Solo si habla mal de todos']},
 {'pregunta': '¿Es mejor admitir que has perdido interés o ir alejándote poco a poco?',
  'opciones': ['Admitirlo claramente', 'Alejarse evita daño', 'Depende del vínculo', 'Siempre hablarlo']},
 {'pregunta': '¿Perdonarías que un amigo no te defendiera delante de otros?',
  'opciones': ['Sí, quizá se bloqueó',
               'No, la lealtad se demuestra',
               'Depende de la situación',
               'Lo hablaría antes']},
 {'pregunta': '¿Es correcto alejarte de un amigo porque su vida se ha vuelto demasiado negativa?',
  'opciones': ['Sí, hay que cuidarse',
               'No, cuando está mal te necesita',
               'Pondría límites',
               'Depende de si busca ayuda']},
 {'pregunta': '¿Te molestaría que un amigo mantuviera relación con alguien que te hizo mucho daño?',
  'opciones': ['Sí, esperaría lealtad',
               'No, sus relaciones son suyas',
               'Depende de lo que pasó',
               'Me dolería aunque lo aceptara']},
 {'pregunta': '¿Una amistad virtual puede ser tan real como una presencial?',
  'opciones': ['Sí', 'No', 'Depende de la conexión', 'Puede ser incluso más íntima']},
 {'pregunta': '¿Debes decirle a un amigo que su pareja no te gusta?',
  'opciones': ['Sí, con tacto', 'No, salvo algo grave', 'Depende de por qué', 'Solo si pregunta']},
 {'pregunta': '¿Puede haber amistad auténtica si una persona siente atracción?',
  'opciones': ['Sí, si sabe gestionarlo', 'No', 'Depende de la intensidad', 'Solo con límites claros']},
 {'pregunta': '¿Está bien usar una excusa falsa para no quedar?',
  'opciones': ['Sí, evita conflictos',
               'No, mejor sinceridad',
               'Depende de la confianza',
               'Una excusa piadosa no hace daño']},
 {'pregunta': '¿Prestar dinero a un amigo fortalece o destruye amistades?',
  'opciones': ['Puede fortalecer', 'Suele destruirlas', 'Depende de la cantidad', 'Nunca presto']},
 {'pregunta': '¿Una disculpa sin cambio de comportamiento sirve de algo?',
  'opciones': ['No, son palabras', 'Sí, reconoce el daño', 'Depende del tiempo', 'Solo una vez']},
 {'pregunta': '¿Es mejor caer bien o ser respetado?',
  'opciones': ['Caer bien', 'Ser respetado', 'Las dos', 'Depende del entorno']},
 {'pregunta': "¿Decir 'yo soy así' es sinceridad o excusa para no cambiar?",
  'opciones': ['Sinceridad', 'Excusa', 'Depende de lo que justifique', 'Casi siempre excusa']},
 {'pregunta': '¿La intuición suele acertar o solo confirma nuestros miedos?',
  'opciones': ['Suele acertar', 'Suele exagerar', 'Depende de la experiencia', 'Es una mezcla']},
 {'pregunta': '¿Perdonar siempre te hace más fuerte o más fácil de herir?',
  'opciones': ['Más fuerte', 'Más vulnerable', 'Depende de los límites', 'Perdonar no obliga a quedarse']},
 {'pregunta': '¿La gente muestra su verdadera personalidad cuando se enfada?',
  'opciones': ['Sí', 'No, el enfado distorsiona', 'Muestra una parte real', 'Depende de cómo lo gestione']},
 {'pregunta': '¿Ser directo justifica hablar sin tacto?',
  'opciones': ['Sí',
               'No, es falta de educación',
               'Depende de la situación',
               'Se puede ser directo y respetuoso']},
 {'pregunta': '¿Es egoísta priorizar siempre tu paz mental?',
  'opciones': ['No, es necesario',
               'Sí, si dañas a otros',
               'Depende de cómo',
               'La paz no justifica huir de todo']},
 {'pregunta': '¿Cambiar de opinión después de una discusión es perder?',
  'opciones': ['No, es madurez',
               'Sí, si es por presión',
               'Depende de por qué',
               'Nunca debería verse como perder']},
 {'pregunta': '¿La sinceridad sin empatía es crueldad?',
  'opciones': ['Sí', 'No', 'Depende de la forma', 'La intención importa']},
 {'pregunta': '¿Una mala etapa justifica tratar mal a los demás?',
  'opciones': ['Sí, a veces', 'No, explica pero no justifica', 'Depende de la gravedad', 'Solo si repara']},
 {'pregunta': '¿La gente valora más lo que le cuesta conseguir?',
  'opciones': ['Sí', 'No necesariamente', 'Depende de la persona', 'A veces idealiza el esfuerzo']},
 {'pregunta': '¿Las segundas oportunidades deberían tener fecha de caducidad?',
  'opciones': ['Sí', 'No', 'Depende de la falta', 'La oportunidad exige cambios']},
 {'pregunta': '¿El éxito cambia a las personas o revela quiénes eran?',
  'opciones': ['Las cambia', 'Las revela', 'Ambas', 'Depende de cómo llegue']},
 {'pregunta': '¿La soledad elegida es libertad o protección?',
  'opciones': ['Libertad', 'Protección', 'Ambas', 'Depende de si se disfruta']},
 {'pregunta': '¿La lealtad debe estar por encima de la verdad?',
  'opciones': ['Sí', 'No, la verdad primero', 'Depende de la situación', 'Lealtad no es encubrir']},
 {'pregunta': '¿Es peor ser hipócrita o cruelmente sincero?',
  'opciones': ['Hipócrita', 'Cruelmente sincero', 'Ambos', 'Depende del daño']},
 {'pregunta': '¿Mentir para proteger la autoestima de alguien está bien?',
  'opciones': ['Sí', 'No, tacto y verdad', 'Depende de la importancia', 'Solo sin consecuencias']},
 {'pregunta': '¿La gente debería separar al artista de su obra?',
  'opciones': ['Sí', 'No', 'Depende de lo que hizo', 'Solo si no hay beneficio económico']},
 {'pregunta': '¿Es correcto grabar una discusión para protegerte?',
  'opciones': ['Sí, como prueba',
               'No, invade privacidad',
               'Solo si temes manipulación',
               'Depende del contexto']},
 {'pregunta': '¿Publicar una conversación privada para defenderte puede justificarse?',
  'opciones': ['Sí, si te difaman',
               'No, lo privado es privado',
               'Solo ocultando datos',
               'Depende de la gravedad']},
 {'pregunta': '¿La gente perdona más a quien es atractivo?',
  'opciones': ['Sí', 'No', 'Depende del entorno', 'Más de lo que admitimos']},
 {'pregunta': '¿Ser demasiado independiente dificulta crear vínculos?',
  'opciones': ['Sí, levanta muros', 'No', 'Depende de si sabes pedir ayuda', 'Puede asustar']},
 {'pregunta': '¿Los celos son una prueba de amor o inseguridad?',
  'opciones': ['Prueba de amor', 'Inseguridad', 'Ambas', 'Depende de cómo se gestionen']},
 {'pregunta': '¿Se puede amar bien sin quererse a uno mismo?',
  'opciones': ['Sí, aunque cuesta', 'No', 'Depende del apoyo', 'El amor propio se aprende']},
 {'pregunta': '¿Una persona debería avisar que no busca nada serio desde el principio?',
  'opciones': ['Sí', 'No, puede surgir después', 'Cuando vea interés', 'Depende']},
 {'pregunta': '¿Es válido dejar una cita porque las fotos no se parecían a la persona?',
  'opciones': ['Sí, hubo engaño',
               'No, es humillante',
               'Depende de cuánto cambien',
               'Terminaría con educación']},
 {'pregunta': '¿Dar atención intermitente es manipulación aunque no sea intencional?',
  'opciones': ['Sí', 'No, puede ser despiste', 'Depende del patrón', 'El efecto importa']},
 {'pregunta': '¿Es correcto mantener a alguien como opción por si otra relación falla?',
  'opciones': ['No, es utilizarlo',
               'Sí, si no prometes nada',
               'Depende de si lo sabe',
               'Casi nunca es limpio']},
 {'pregunta': '¿Es razonable pedir una prueba de ITS antes de tener relaciones sin preservativo?',
  'opciones': ['Sí', 'No, rompe espontaneidad', 'Solo si ambos la hacen', 'Siempre debería hablarse']},
 {'pregunta': '¿Es válido no querer salir con alguien por tener hijos?',
  'opciones': ['Sí, cada uno conoce sus límites',
               'No, es injusto',
               'Depende de la situación',
               'Mejor ser sincero']},
 {'pregunta': '¿Te parecería mal que alguien siguiera usando apps de citas mientras os conocéis?',
  'opciones': ['Sí', 'No, no hay exclusividad', 'Depende del tiempo', 'Hay que hablarlo']},
 {'pregunta': '¿Una relación abierta puede arreglar una relación que ya va mal?',
  'opciones': ['Sí', 'No, suele empeorarla', 'Solo si ambos querían antes', 'Nunca como parche']},
 {'pregunta': '¿Es válido terminar porque la otra persona no quiere casarse?',
  'opciones': ['Sí, proyectos incompatibles',
               'No, el amor debería bastar',
               'Depende de la importancia',
               'Mejor terminar que forzar']},
 {'pregunta': '¿Es correcto pedir a tu pareja que deje de hablar con alguien que le coquetea?',
  'opciones': ['Sí', 'No, debe decidirlo', 'Depende de cómo responda', 'Lo hablaría sin exigir']},
 {'pregunta': '¿Te parecería red flag que alguien hable mal de todos sus ex?',
  'opciones': ['Sí, probablemente el patrón es esa persona',
               'No, pudo tener mala suerte',
               'Depende de los relatos',
               'Es una señal']},
 {'pregunta': '¿Es posible enamorarse sin haberse visto en persona?',
  'opciones': ['Sí', 'No, idealizas', 'Puede haber conexión, no amor completo', 'Depende del tiempo']},
 {'pregunta': '¿Te acostarías con la expareja de una amistad si han pasado años?',
  'opciones': ['Sí', 'No, hay códigos', 'Solo hablándolo antes', 'Depende de la amistad']},
 {'pregunta': '¿Es infidelidad besar a alguien borracho si luego no recuerda nada?',
  'opciones': ['Sí', 'No, sin conciencia no', 'Depende del grado', 'Es grave aunque no recuerde']},
 {'pregunta': '¿Crees que quien ama de verdad siempre encuentra tiempo?',
  'opciones': ['Sí, las prioridades se notan',
               'No, la vida desborda',
               'Depende de la etapa',
               'Al menos comunica']},
 {'pregunta': '¿Se puede confundir paz con aburrimiento en una relación sana?',
  'opciones': ['Sí', 'No', 'Depende de experiencias previas', 'A veces el drama crea adicción']},
 {'pregunta': '¿La química sexual compensa una mala compatibilidad emocional?',
  'opciones': ['Sí, un tiempo', 'No', 'Depende de lo que busquen', 'Solo si no quieren algo serio']},
 {'pregunta': '¿Es válido no querer convivir nunca con una pareja?',
  'opciones': ['Sí', 'No, limita el compromiso', 'Depende del acuerdo', 'Puede haber amor sin convivencia']},
 {'pregunta': '¿La atracción puede construirse con el tiempo?',
  'opciones': ['Sí',
               'No, debe existir al principio',
               'Depende de la persona',
               'La conexión puede transformarla']},
 {'pregunta': '¿Es peor una infidelidad emocional o física?',
  'opciones': ['Emocional', 'Física', 'Ambas', 'Depende de la duración']},
 {'pregunta': '¿Se puede amar sin confiar?',
  'opciones': ['Sí, pero duele', 'No', 'Puede quedar apego', 'Depende de por qué se perdió']},
 {'pregunta': '¿Es válido necesitar tiempo a solas aunque la relación vaya bien?',
  'opciones': ['Sí', 'No, si amas quieres compartir', 'Depende de cuánto', 'Cada cual necesita espacio']},
 {'pregunta': '¿La estabilidad económica debería influir al elegir pareja?',
  'opciones': ['Sí, mucho', 'No, nada', 'Importa la responsabilidad', 'Depende del proyecto']},
 {'pregunta': '¿Aceptarías que tu pareja saliera de fiesta sin ti con frecuencia?',
  'opciones': ['Sí', 'No', 'Depende de la frecuencia', 'Mientras haya equilibrio']},
 {'pregunta': '¿Una pareja debe tener acceso a tus conversaciones con amistades?',
  'opciones': ['No',
               'Sí, si no ocultas nada',
               'Solo con permiso de la otra persona',
               'Nunca por obligación']},
 {'pregunta': '¿Es correcto pedir una pausa en vez de terminar?',
  'opciones': ['Sí', 'No, suele ser ruptura aplazada', 'Depende de las reglas', 'Solo con fecha y acuerdos']},
 {'pregunta': '¿Es válido no querer una relación con alguien que trabaja demasiadas horas?',
  'opciones': ['Sí', 'No, es falta de apoyo', 'Depende de si es temporal', 'Cada uno elige su vida']},
 {'pregunta': '¿Una relación necesita proyectos comunes para durar?',
  'opciones': ['Sí', 'No, basta con quererse', 'Algunos sí', 'Depende de la etapa']},
 {'pregunta': '¿Es correcto hacer una prueba de fidelidad con una cuenta falsa?',
  'opciones': ['No, es manipulación',
               'Sí, si hay sospechas',
               'Depende de las pruebas',
               'Si lo necesitas, ya va mal']},
 {'pregunta': '¿Es válido sentir atracción por otras personas estando en pareja?',
  'opciones': ['Sí, es humano', 'No, si amas no miras', 'Sentir sí, actuar no', 'Depende de la intensidad']},
 {'pregunta': '¿Es justo juzgar a alguien por haber tenido muchas relaciones?',
  'opciones': ['No', 'Sí, dice algo de sus patrones', 'Depende de cómo fueron', 'Importa el presente']},
 {'pregunta': '¿Es válido terminar porque no comparte tu sentido del humor?',
  'opciones': ['Sí', 'No, es menor', 'Depende de cuánto pese', 'El humor conecta mucho']},
 {'pregunta': '¿Es correcto mantener una relación por los hijos aunque ya no haya amor?',
  'opciones': ['Sí, por estabilidad',
               'No, los hijos perciben todo',
               'Depende del conflicto',
               'Mejor separación sana']},
 {'pregunta': '¿Una persona puede amar y no saber cuidar?',
  'opciones': ['Sí', 'No, amar implica cuidar', 'Puede amar, pero no basta', 'Depende de si aprende']},
 {'pregunta': '¿Es mejor que tu pareja sea tu mejor amistad o mantener ambas cosas separadas?',
  'opciones': ['Que sea mi mejor amistad', 'Separarlo', 'Puede ser ambas', 'Depende']},
 {'pregunta': '¿Una relación necesita compatibilidad sexual de base?',
  'opciones': ['Sí', 'No, se aprende', 'Ambas cosas', 'Depende de la comunicación']},
 {'pregunta': '¿Es correcto borrar comentarios críticos de tus redes?',
  'opciones': ['Sí, es tu espacio',
               'No, es censura',
               'Depende de si son respetuosos',
               'Crítica sí, ataques no']},
 {'pregunta': '¿Dejar en visto es una respuesta?',
  'opciones': ['Sí, bastante clara',
               'No, es falta de educación',
               'Depende del mensaje',
               'A veces el silencio responde']},
 {'pregunta': '¿Es válido eliminar a alguien de redes después de una discusión?',
  'opciones': ['Sí', 'No, es infantil', 'Depende de si termina la relación', 'A veces hace falta distancia']},
 {'pregunta': "¿Los 'me gusta' tienen significado real?",
  'opciones': ['Sí, comunican interés',
               'No, son automáticos',
               'Depende de la frecuencia',
               'El contexto lo cambia todo']},
 {'pregunta': '¿Los audios largos son cercanía o falta de consideración?',
  'opciones': ['Cercanía', 'Falta de consideración', 'Depende del contexto', 'Con aviso, todo mejora']},
 {'pregunta': '¿Es correcto reenviar un audio privado?',
  'opciones': ['No', 'Sí, para pedir consejo', 'Solo con permiso', 'Depende del contenido']},
 {'pregunta': '¿La gente debería pedir permiso antes de añadirte a un grupo?',
  'opciones': ['Sí', 'No, se puede salir', 'Depende del grupo', 'Como mínimo avisar']},
 {'pregunta': '¿El humor justifica bromas que incomodan?',
  'opciones': ['No, si incomoda se para',
               'Sí, la gente se ofende por todo',
               'Depende de la intención',
               'Importa más el impacto']},
 {'pregunta': '¿Es correcto dejar de hablar con familiares tóxicos?',
  'opciones': ['Sí', 'No, la familia es la familia', 'Depende del daño', 'Poner distancia es válido']},
 {'pregunta': '¿Debes perdonar a un familiar por ser familia?',
  'opciones': ['Sí', 'No', 'Depende de si cambia', 'Perdonar no obliga a convivir']},
 {'pregunta': '¿Es válido no cuidar a familiares que no te cuidaron?',
  'opciones': ['Sí', 'No, hay que ser mejor', 'Depende de la situación', 'Ayudar no es olvidar']},
 {'pregunta': '¿Es mejor un trabajo bien pagado que odias o uno que amas pero apenas te permite vivir?',
  'opciones': ['Bien pagado', 'Mal pagado que amo', 'Buscar equilibrio', 'Depende de las responsabilidades']},
 {'pregunta': '¿Dejarías un trabajo estable por un sueño incierto?',
  'opciones': ['Sí', 'No', 'Solo con ahorros', 'Depende de la oportunidad']},
 {'pregunta': '¿Debes responder mensajes laborales fuera de horario?',
  'opciones': ['Sí, si urge', 'No, nunca', 'Solo si compensan', 'Depende del puesto']},
 {'pregunta': '¿Es válido mentir en una entrevista de trabajo?',
  'opciones': ['Sí, todos exageran', 'No', 'Solo adornar', 'Depende de la mentira']},
 {'pregunta': '¿Es correcto usar contactos para conseguir empleo?',
  'opciones': ['Sí', 'No, es injusto', 'Depende de si estás preparado', 'Abren puertas, no garantizan']},
 {'pregunta': '¿Es egoísta no prestar dinero aunque puedas?',
  'opciones': ['No, es tu dinero',
               'Sí, si alguien cercano lo necesita',
               'Depende de la razón',
               'Ayudar no siempre es prestar']},
 {'pregunta': '¿Ocultar deudas a una pareja es infidelidad financiera?',
  'opciones': ['Sí', 'No, es personal', 'Solo si comparten gastos', 'Depende de la cantidad']},
 {'pregunta': '¿Es mejor ahorrar mucho o disfrutar ahora?',
  'opciones': ['Ahorrar', 'Disfrutar', 'Equilibrio', 'Depende de la etapa']},
 {'pregunta': '¿Una persona que gana mucho debe pagar más en pareja?',
  'opciones': ['Sí, proporcional', 'No, mitad y mitad', 'Depende del acuerdo', 'Importa la equidad']},
 {'pregunta': '¿Es más importante tener tiempo o dinero?',
  'opciones': ['Tiempo', 'Dinero', 'Equilibrio', 'Depende de la etapa']},
 {'pregunta': '¿Salvarías a cinco desconocidos perjudicando gravemente a una persona cercana?',
  'opciones': ['Sí', 'No', 'Depende de quién sea', 'No podría decidir']},
 {'pregunta': '¿Mentirías para evitar un sufrimiento que no puede cambiar nada?',
  'opciones': ['Sí', 'No', 'Depende de la verdad', 'Solo temporalmente']},
 {'pregunta': '¿Robar comida para alimentar a tu familia está moralmente mal?',
  'opciones': ['Sí, sigue siendo robo',
               'No, la necesidad justifica',
               'Depende de alternativas',
               'Ilegal, pero comprensible']},
 {'pregunta': '¿Denunciarías a un familiar por un delito grave?',
  'opciones': ['Sí', 'No', 'Le pediría que se entregara', 'Depende del delito']},
 {'pregunta': '¿Es legítimo vengarse si la justicia no funciona?',
  'opciones': ['Sí', 'No', 'Depende del daño', 'Entiendo el impulso, no lo haría']},
 {'pregunta': '¿Es más importante respetar la ley o hacer lo justo?',
  'opciones': ['La ley', 'Lo justo', 'Depende de la ley', 'Lo ideal es cambiarla']},
 {'pregunta': '¿Preferirías saber cuándo vas a morir o cómo?',
  'opciones': ['Cuándo', 'Cómo', 'Ninguna', 'Depende de si puedo cambiarlo']},
 {'pregunta': '¿Aceptarías vivir una vida perfecta sabiendo que es una simulación?',
  'opciones': ['Sí', 'No', 'Depende de si puedo salir', 'La felicidad seguiría siendo real']},
 {'pregunta': '¿Es mejor ser querido por una versión falsa de ti o rechazado por ser auténtico?',
  'opciones': ['Querido aunque adaptado', 'Rechazado pero auténtico', 'Punto medio', 'Nadie muestra todo']},
 {'pregunta': '¿La intención importa más que el impacto?',
  'opciones': ['Sí', 'No', 'Ambas', 'Depende de si repara']},
 {'pregunta': '¿Es válido no perdonar nunca?',
  'opciones': ['Sí', 'No, te daña', 'Puedes sanar sin perdonar', 'Depende del caso']},
 {'pregunta': '¿Es correcto expulsar de un grupo a alguien que no rompe normas pero genera tensión '
              'constante?',
  'opciones': ['Sí', 'No', 'Primero hablaría', 'Depende de la tensión']},
 {'pregunta': '¿Es correcto pedir participación mínima en un grupo social?',
  'opciones': ['Sí', 'No', 'Depende del objetivo', 'Avisaría antes']},
 {'pregunta': '¿Los administradores deben explicar siempre una expulsión?',
  'opciones': ['Sí', 'No, algunas razones son privadas', 'Al menos al expulsado', 'Depende de la gravedad']},
 {'pregunta': '¿Una broma deja de ser broma cuando solo se ríe quien la hace?',
  'opciones': ['Sí', 'No, la intención cuenta', 'Depende de si se repite', 'Si piden parar, se para']},
 {'pregunta': '¿Es peor alguien que habla demasiado o alguien que nunca participa?',
  'opciones': ['El que habla demasiado',
               'El que nunca participa',
               'Depende de la calidad',
               'Ambos desequilibran']},
 {'pregunta': '¿Es correcto exigir foto de perfil en un grupo?',
  'opciones': ['Sí, da seguridad',
               'No, invade privacidad',
               'Sí, si puede ser cualquier imagen',
               'Depende del grupo']},
 {'pregunta': '¿Y exigir un audio breve de presentación?',
  'opciones': ['Sí, humaniza',
               'No, es demasiado',
               'Sí, si dura pocos segundos',
               'Depende de cómo se explique']},
 {'pregunta': '¿Es válido expulsar a quien no se presenta después de varios avisos?',
  'opciones': ['Sí', 'No', 'Depende del tiempo dado', 'Un último aviso']},
 {'pregunta': '¿La participación se mide por cantidad o calidad?',
  'opciones': ['Cantidad', 'Calidad', 'Ambas', 'Depende del grupo']},
 {'pregunta': '¿Un grupo debe priorizar privacidad o crecimiento?',
  'opciones': ['Privacidad', 'Crecimiento', 'Equilibrio', 'Depende de los riesgos']},
 {'pregunta': '¿Los miembros deberían poder escribir por privado sin pedir permiso?',
  'opciones': ['Sí', 'No', 'Solo tras hablar en el grupo', 'Depende del mensaje']},
 {'pregunta': '¿Es válido hacer limpieza periódica de miembros inactivos?',
  'opciones': ['Sí', 'No', 'Con avisos previos', 'Depende del límite']},
 {'pregunta': '¿Las normas deben aplicarse igual a veteranos y nuevos?',
  'opciones': ['Sí', 'No, el contexto importa', 'Sí, con margen humano', 'Los veteranos deben dar ejemplo']},
 {'pregunta': '¿Un grupo pierde identidad cuando crece demasiado?',
  'opciones': ['Sí', 'No, si se modera bien', 'Depende de la cultura', 'Puede transformarse']},
 {'pregunta': '¿Es mejor cien miembros activos o mil silenciosos?',
  'opciones': ['Cien activos', 'Mil silenciosos', 'Depende del objetivo', 'La calidad gana']},
 {'pregunta': '¿Los silenciosos aportan leyendo o son decoración?',
  'opciones': ['Aportan presencia', 'Son decoración', 'Depende de si reaccionan', 'Un grupo necesita más']},
 {'pregunta': '¿Un grupo debe adaptarse a los nuevos o los nuevos al grupo?',
  'opciones': ['El grupo', 'Los nuevos', 'Ambos', 'La identidad debe mantenerse']},
 {'pregunta': '¿Es correcto usar bots para animar un grupo que ya habla solo?',
  'opciones': ['Sí', 'No, son pesados', 'Solo con poca frecuencia', 'Depende de la función']},
 {'pregunta': '¿Una comunidad puede sentirse familia sin conocerse en persona?',
  'opciones': ['Sí', 'No', 'Puede sentirse cercana, no familia', 'Depende del tiempo']}]
