import random

# DADONET - 450 preguntas
# 150 SALSEO + 150 SIN FILTRO + 150 BOMBA
# No repite una pregunta de una categoría hasta haber usado todas las de esa categoría.

SALSEO = ['¿Quién del grupo te cayó mejor desde el primer día?',
 '¿Quién del grupo te cayó peor al principio y ahora te cae mejor?',
 '¿Quién te cayó bien al principio y ahora te genera más dudas?',
 '¿Quién del grupo crees que habla por privado con más gente de la que reconoce?',
 '¿Quién crees que se hace más el inocente de lo que realmente es?',
 '¿Quién del grupo te genera más curiosidad aunque apenas hayas hablado con esa persona?',
 '¿Con quién del grupo crees que tendrías una conversación de horas sin aburrirte?',
 '¿Quién del grupo crees que podría sorprenderte muchísimo en persona?',
 '¿Quién crees que tiene una personalidad muy distinta por privado que en el grupo?',
 '¿Quién del grupo crees que sabe más salseos de los que cuenta?',
 '¿Quién crees que observa mucho más de lo que participa?',
 '¿Quién del grupo crees que tiene más facilidad para ligar sin proponérselo?',
 '¿Quién crees que tiene más gente detrás de lo que aparenta?',
 '¿Quién del grupo sería tu compañero/a perfecto/a para una noche de fiesta?',
 '¿Con quién del grupo te irías de viaje un fin de semana sin conocerlo mucho más?',
 '¿Quién crees que sería capaz de desaparecer del grupo y volver un mes después como si nada?',
 '¿Quién del grupo crees que se mete en más líos sentimentales?',
 '¿Quién crees que podría acabar emparejado con alguien del grupo?',
 '¿Quién del grupo crees que tiene más paciencia para aguantar dramas?',
 '¿Quién sería la peor persona para confiarle un secreto pequeño?',
 '¿Quién del grupo te parece más difícil de conocer de verdad?',
 '¿Quién crees que tiene más doble vida entre lo que cuenta aquí y su vida real?',
 '¿Quién del grupo crees que es más celoso/a de lo que reconoce?',
 '¿Quién crees que se engancha emocionalmente más rápido?',
 '¿Quién del grupo crees que tarda menos en cansarse de alguien?',
 '¿Quién crees que tiene más posibilidades de enamorarse de alguien del grupo?',
 '¿Quién del grupo crees que podría tener una relación secreta y nadie se enteraría?',
 '¿Quién te parece más probable que haya cotilleado el perfil entero de alguien del grupo?',
 '¿Quién crees que borra mensajes después de mandarlos porque se arrepiente?',
 "¿Quién del grupo sería capaz de montar una película mental por un simple 'visto'?",
 '¿Quién crees que más disimula cuando alguien le gusta?',
 '¿Quién del grupo crees que se pica más cuando le llevan la contraria?',
 '¿Quién crees que tendría más éxito organizando una quedada del grupo?',
 '¿Quién del grupo crees que sería más divertido/a de conocer cara a cara?',
 '¿Quién crees que podría acabar siendo tu mejor amigo/a de aquí?',
 '¿A quién del grupo le preguntarías primero si quisieras enterarte de un salseo?',
 '¿Quién crees que se da cuenta antes que nadie de quién está tonteando con quién?',
 '¿Quién del grupo crees que podría guardar un secreto durante años?',
 '¿Quién del grupo te parece más imprevisible?',
 '¿Quién crees que podría caerle bien a casi todo el mundo en persona?',
 '¿Quién del grupo te parece que da una imagen más dura de lo que realmente es?',
 '¿Quién crees que aparenta ser más tranquilo/a de lo que es?',
 '¿Quién del grupo te parece que podría tener más anécdotas que todavía no ha contado?',
 '¿Quién crees que escucha más audios ajenos con cara de detective?',
 '¿Quién del grupo te parece más probable que tenga capturas guardadas?',
 '¿Quién crees que es más de enterarse de algo y hacerse el loco/a?',
 '¿Quién del grupo te parece que podría enamorarse de una voz?',
 '¿Quién crees que se fijaría primero en alguien nuevo que entra al grupo?',
 '¿Quién del grupo podría hacer amistad con cualquiera en cinco minutos?',
 '¿Quién crees que sería el más cotilla en una quedada?',
 '¿Quién del grupo tiene más pinta de recordar absolutamente todo lo que se dice?',
 '¿Quién crees que podría ser el primero en darse cuenta de una mentira?',
 '¿Quién del grupo parece más fácil de picar?',
 '¿Quién crees que se toma mejor las bromas y quién peor?',
 '¿Quién del grupo parece tener más paciencia con la gente intensa?',
 '¿Quién crees que sería el primero en meterse en un debate innecesario?',
 '¿Quién del grupo tiene más pinta de cambiar totalmente tu opinión al conocerlo en persona?',
 '¿Quién crees que es más de hablar mucho por privado y poco en el grupo?',
 '¿Quién del grupo parece más probable que se encariñe con alguien sin querer?',
 '¿Quién crees que tendría más posibilidades de caer bien a tu círculo de amigos?',
 '¿Quién del grupo parece tener más historias de ex que contar?',
 '¿Quién crees que sería el primero en enterarse de un lío sentimental dentro del grupo?',
 "¿Quién del grupo te parece más probable que diga 'me da igual' cuando claramente no le da igual?",
 '¿Quién crees que se enamoraría de alguien que no le conviene?',
 "¿Quién del grupo tiene más pinta de haber dicho 'yo nunca haría eso' y luego hacerlo?",
 '¿Quién crees que sería el más divertido/a en un viaje de grupo?',
 '¿Quién te parece más probable que tenga una opinión secreta sobre casi todos?',
 '¿Quién del grupo parece que podría caer mal sin querer por su forma de escribir?',
 '¿Quién crees que sería el primero en pedir perdón después de una discusión?',
 '¿Quién del grupo sería más difícil de olvidar después de conocerlo?',
 '¿Quién crees que podría tener más admiradores silenciosos?',
 '¿Quién del grupo parece que daría el mejor consejo sentimental?',
 '¿Quién crees que daría el peor consejo sentimental pero con muchísima seguridad?',
 '¿Quién del grupo parece más probable que reaparezca en la vida de un ex?',
 '¿Quién crees que tiene más facilidad para detectar cuando alguien está mintiendo?',
 '¿Quién del grupo parece más probable que se enamore por cómo le tratan y no por el físico?',
 '¿Quién crees que podría liarla más en una quedada sin proponérselo?',
 '¿Quién del grupo parece tener más carácter del que muestra?',
 '¿Quién crees que puede ser mucho más tímido/a en persona de lo que parece aquí?',
 '¿Quién del grupo parece que se guardaría algo importante para evitar drama?',
 '¿Quién del grupo crees que sería capaz de caerle mal a alguien y no enterarse nunca?',
 '¿Quién parece que tendría más facilidad para hacer amigos en cualquier ciudad?',
 '¿Quién del grupo crees que tiene más paciencia para escuchar dramas ajenos?',
 '¿Quién sería el primero en organizar una escapada improvisada?',
 '¿Quién crees que podría acabar siendo inseparable de alguien con quien ahora apenas habla?',
 '¿Quién del grupo tiene más pinta de tener un pasado sentimental bastante entretenido?',
 '¿Quién crees que aparenta seguridad pero en realidad duda mucho de sí mismo/a?',
 '¿Quién del grupo parece más probable que se arrepienta de algo justo después de decirlo?',
 '¿Quién crees que tendría más posibilidades de hacer una amistad inesperada con alguien muy distinto?',
 '¿Quién del grupo te parece más probable que sepa guardar las apariencias aunque esté enfadado/a?',
 '¿Quién crees que tiene más facilidad para leer el ambiente de una conversación?',
 '¿Quién del grupo podría acabar cayéndote genial después de una primera impresión regular?',
 '¿Quién parece más probable que tenga una vida mucho más interesante de lo que cuenta?',
 '¿Quién crees que podría tener un talento secreto que sorprendería a todos?',
 '¿Quién del grupo parece más probable que esté siempre pendiente de todo aunque no escriba?',
 '¿Quién crees que sería capaz de recordar una frase tuya de hace meses?',
 '¿Quién del grupo parece más de observar primero y hablar después?',
 '¿Quién crees que podría ser el más diplomático en una discusión fuerte?',
 '¿Quién del grupo parece más probable que tenga un grupo de amigos completamente distinto a lo que imaginas?',
 '¿Quién crees que sería más capaz de perdonar una metedura de pata seria?',
 '¿Quién del grupo parece más probable que se tome algo personal aunque diga que no?',
 '¿Quién crees que podría sorprenderte por ser mucho más cariñoso/a en persona?',
 '¿Quién del grupo parece que puede estar enfadado/a contigo y seguir hablándote con normalidad?',
 '¿Quién crees que tiene más probabilidades de engancharse a una conversación de madrugada?',
 '¿Quién del grupo parece que se adapta mejor a cualquier tipo de persona?',
 '¿Quién crees que sería más difícil de pillar mintiendo en una tontería?',
 '¿Quién del grupo parece más probable que cambie de opinión sobre alguien de un día para otro?',
 '¿Quién crees que tendría más posibilidades de ser el mediador en un conflicto del grupo?',
 '¿Quién del grupo parece más probable que esté pendiente de quién entra y quién sale?',
 '¿Quién crees que sería capaz de detectar tensión entre dos personas antes que nadie?',
 '¿Quién del grupo parece más probable que se vuelva imprescindible en una quedada?',
 '¿Quién crees que tendría más posibilidades de acabar hablando con alguien hasta el amanecer?',
 '¿Quién del grupo parece más probable que se ilusione con planes pequeños?',
 '¿Quién crees que tiene más posibilidades de caer bien a alguien totalmente opuesto a él/ella?',
 '¿Quién del grupo parece más probable que no cuente nunca todo lo que piensa?',
 '¿Quién crees que sería más divertido/a improvisando un plan sin organizar nada?',
 '¿Quién del grupo parece más probable que tenga un humor muy distinto en persona?',
 '¿Quién crees que podría ser mucho más sensible de lo que deja ver?',
 '¿Quién del grupo parece más probable que recuerde fechas importantes de los demás?',
 '¿Quién crees que sería el primero en notar que alguien está raro aunque diga que está bien?',
 '¿Quién del grupo parece más probable que tenga más amigos de distintas edades?',
 '¿Quién crees que podría ser el más generoso/a sin hacer ruido?',
 '¿Quién del grupo parece más probable que se arrepienta de no haber hablado más con alguien?',
 '¿Quién crees que tendría más posibilidades de convertirse en el confidente de medio grupo?',
 '¿Quién del grupo parece más probable que sea completamente distinto cuando está enfadado/a?',
 '¿Quién crees que podría acabar llevándose genial con alguien con quien ahora choca?',
 '¿Quién del grupo parece más probable que tenga una historia pendiente con alguien del pasado?',
 '¿Quién crees que sería el más difícil de impresionar?',
 '¿Quién del grupo parece más probable que tenga una opinión muy formada sobre todos?',
 '¿Quién crees que tendría más posibilidades de caerle bien a tu familia?',
 '¿Quién del grupo parece más probable que se vaya de una discusión antes de explotar?',
 '¿Quién crees que podría ser el más protector con sus amigos?',
 '¿Quién del grupo parece más probable que diga una verdad incómoda cuando nadie más se atreve?',
 '¿Quién crees que tendría más posibilidades de defender a alguien aunque no sea su amigo?',
 '¿Quién del grupo parece más probable que cambie totalmente cuando coge confianza?',
 '¿Quién crees que podría ser el más detallista con la gente que quiere?',
 '¿Quién del grupo parece más probable que eche de menos a alguien y no lo diga?',
 '¿Quién crees que tendría más posibilidades de guardar una conversación importante durante años?',
 '¿Quién del grupo parece más probable que tenga más paciencia para conocer a alguien de verdad?',
 '¿Quién crees que sería el primero en notar cuando alguien se está alejando?',
 '¿Quién del grupo parece más probable que necesite tiempo para confiar de verdad?',
 '¿Quién crees que podría ser el más leal cuando las cosas se complican?',
 '¿Quién del grupo parece más probable que tenga una vida social mucho más activa de lo que aparenta?',
 '¿Quién crees que sería el primero en darse cuenta de que dos personas se gustan?',
 '¿Quién del grupo parece más probable que se vuelva muy cercano a alguien de forma inesperada?',
 '¿Quién crees que podría ser el más cabezota cuando cree que tiene razón?',
 '¿Quién del grupo parece más probable que tenga una paciencia infinita hasta que un día explota?',
 '¿Quién crees que sería capaz de mantener una amistad durante años aunque apenas se vean?',
 '¿Quién del grupo parece más probable que se arrepienta de una primera impresión demasiado rápida?',
 '¿Quién crees que podría acabar siendo una de las mayores sorpresas del grupo?']

SIN_FILTRO = ['¿Quién del grupo te atrae más físicamente?',
 '¿A quién del grupo besarías si tuvieras que elegir ahora mismo?',
 '¿Con quién del grupo crees que tendrías más química en persona?',
 '¿Con quién del grupo tendrías una cita solo por curiosidad?',
 '¿Quién del grupo te parece más peligroso/a sentimentalmente?',
 '¿Quién crees que sería peor pareja?',
 '¿Quién crees que sería mejor pareja?',
 '¿Quién del grupo crees que rompería más corazones?',
 '¿Con quién del grupo jamás tendrías nada aunque te lo pusieran facilísimo?',
 '¿Quién crees que está más bueno/a de lo que enseñan sus fotos?',
 '¿Quién del grupo te genera más curiosidad sexual?',
 '¿Quién crees que sería mejor amante?',
 '¿Quién crees que sería peor amante?',
 '¿Con quién del grupo te liarías una noche sabiendo que al día siguiente no pasaría nada?',
 '¿Con quién del grupo no te importaría que surgiera algo inesperado?',
 '¿Quién del grupo crees que podría hacerte perder la cabeza?',
 '¿A quién del grupo bloquearías durante 24 horas solo por tocar los cojones?',
 '¿Quién del grupo te parece más probable que se haya fijado en alguien y no lo reconozca?',
 '¿Quién crees que está tonteando con alguien del grupo aunque diga que no?',
 '¿A quién del grupo le darías una oportunidad si te pidiera una cita?',
 '¿Quién del grupo te parece más probable que tenga un crush secreto?',
 '¿Quién crees que tendría más posibilidades contigo si se lo propusiera?',
 '¿Quién del grupo te parece más probable que ligue por mensaje privado?',
 '¿Quién crees que puede ser más intenso/a cuando le gusta alguien?',
 '¿Quién del grupo crees que se enamora peor?',
 '¿Quién crees que tarda menos en sustituir a una persona cuando una relación termina?',
 '¿Quién del grupo crees que volvería con un ex aunque jurara que jamás lo haría?',
 '¿Quién te parece más probable que haya enviado un mensaje borracho/a y se arrepintiera al día siguiente?',
 '¿Quién crees que sería capaz de tener dos conversaciones románticas abiertas al mismo tiempo?',
 '¿Quién del grupo crees que tiene más posibilidades de estar hablando con alguien del grupo por privado ahora mismo?',
 '¿A quién del grupo te costaría más decirle que no si se lanzara contigo?',
 '¿Quién del grupo te parece más atractivo/a por personalidad que por físico?',
 '¿Quién del grupo te parece más atractivo/a físicamente que por personalidad?',
 '¿Quién crees que podría gustarte mucho más después de conocerlo en persona?',
 '¿Quién crees que podría decepcionarte más al conocerlo en persona?',
 '¿Quién del grupo crees que tiene más posibilidades de ser tóxico/a en pareja?',
 '¿Quién crees que sería más posesivo/a?',
 '¿Quién crees que llevaría peor que su pareja tuviera mucha relación con otras personas del grupo?',
 '¿Quién crees que sería capaz de mirar el móvil de su pareja?',
 '¿Quién del grupo crees que perdonaría una infidelidad?',
 '¿Quién crees que jamás perdonaría una infidelidad?',
 '¿Quién del grupo crees que podría ser infiel y conseguir que nadie se enterara?',
 '¿Quién del grupo crees que tiene más secretos sentimentales?',
 '¿Con quién del grupo tendrías más miedo de engancharte emocionalmente?',
 '¿A quién del grupo te gustaría conocer mejor aunque nunca se lo hayas dicho?',
 '¿Quién del grupo te ha sorprendido para bien últimamente?',
 '¿Quién del grupo te ha decepcionado un poco últimamente?',
 '¿Quién crees que tiene una opinión sobre ti que nunca se atrevería a decirte?',
 '¿De quién del grupo te gustaría saber qué piensa realmente de ti?',
 '¿Quién crees que te juzgó mal cuando entraste al grupo?',
 '¿Quién del grupo crees que te conoce menos de lo que piensa?',
 '¿Quién del grupo crees que sabe exactamente cómo picarte?',
 '¿Quién podría hacerte enfadar más rápido?',
 '¿Con quién del grupo sería más probable que acabaras discutiendo y reconciliándote el mismo día?',
 '¿Quién crees que sería capaz de hacerse el/la duro/a y luego pillarse muchísimo?',
 '¿Quién del grupo crees que tiene más miedo al compromiso?',
 '¿Quién crees que tendría una relación más caótica?',
 '¿Quién del grupo crees que sería el primero en tener algo con otra persona del grupo?',
 '¿Quién te parece que está más acostumbrado/a a salirse con la suya?',
 '¿Quién del grupo crees que tiene más facilidad para manipular una situación a su favor?',
 '¿Quién crees que sería capaz de negar hasta la muerte que alguien le gusta aunque fuera evidente?',
 '¿Quién del grupo te parece más probable que se obsesione con alguien que le da atención intermitente?',
 '¿Quién crees que tiene más posibilidades de liarse con alguien en una quedada?',
 '¿A quién del grupo besarías solo por comprobar si hay química?',
 '¿Quién te parece más probable que tenga una relación de amor-odio con alguien del grupo?',
 '¿Quién del grupo crees que podría hacer ghosting después de una noche intensa?',
 '¿Quién crees que sería capaz de volver a escribir a alguien solo porque lo vio feliz sin él/ella?',
 '¿Quién del grupo te parece más probable que tenga celos sin tener derecho a tenerlos?',
 '¿A quién del grupo te costaría más ver con otra persona?',
 '¿Quién crees que podría confundirte más emocionalmente?',
 '¿Quién del grupo crees que podría gustarte aunque no encaje nada con tu tipo habitual?',
 '¿Quién te parece más probable que se enganche después de decir que solo quiere algo casual?',
 '¿Quién del grupo crees que ha tenido más líos de los que cuenta?',
 '¿Quién crees que sabe exactamente cómo seducir cuando quiere?',
 '¿Quién del grupo te parece más probable que termine pillándose de alguien prohibido?',
 '¿A quién del grupo te daría curiosidad besar aunque no tuvieras intención de nada más?',
 '¿Quién crees que podría tener más química contigo pero también darte más problemas?',
 '¿Quién del grupo sería más difícil de rechazar si se pusiera serio/a contigo?',
 '¿Quién crees que podría ponerse celoso/a sin admitirlo?',
 '¿Quién del grupo te parece más probable que haya fantaseado con alguien de aquí?',
 '¿Quién del grupo te parecería más difícil de sacar de tu cabeza después de una cita?',
 '¿A quién del grupo crees que podrías acabar deseando aunque al principio no te atrajera?',
 '¿Quién te parece más probable que despierte celos en ti sin ser nada tuyo?',
 '¿Con quién del grupo crees que te costaría más mantener una relación puramente amistosa?',
 '¿Quién del grupo te parecería más peligroso si empezara a darte mucha atención?',
 '¿A quién del grupo te sorprendería descubrir que te atrae en persona?',
 '¿Quién crees que podría gustarte mucho y sacarte de quicio al mismo tiempo?',
 '¿Con quién del grupo tendrías una cita sabiendo que seguramente acabaría en discusión?',
 '¿Quién del grupo te parece más probable que te genere curiosidad después de una sola conversación privada?',
 '¿A quién del grupo te costaría más ignorar si empezara a coquetear contigo?',
 '¿Quién crees que sería capaz de hacerte replantearte tu tipo habitual?',
 '¿Quién del grupo te parece más probable que te enganche por cómo habla y no por el físico?',
 '¿Quién crees que podría hacer que te pusieras nervioso/a simplemente con mirarte?',
 '¿Con quién del grupo tendrías más riesgo de confundir amistad con atracción?',
 '¿Quién te parece más probable que acabe gustándote después de una quedada?',
 '¿A quién del grupo le darías una segunda oportunidad después de una mala primera cita?',
 '¿Quién crees que podría hacerte cambiar de opinión sobre una relación casual?',
 '¿Quién del grupo te parece más probable que se vuelva tu debilidad sin darte cuenta?',
 '¿Con quién del grupo crees que sería más difícil cortar el contacto si algo saliera mal?',
 '¿Quién te parece más probable que te haga sentir competencia aunque no quieras?',
 '¿A quién del grupo te daría más curiosidad conocer en una situación completamente distinta?',
 '¿Quién crees que podría sacar tu lado más posesivo/a?',
 '¿Con quién del grupo te sería más difícil fingir que no pasa nada si hubiera química?',
 '¿Quién te parece más probable que se te meta demasiado rápido bajo la piel?',
 '¿A quién del grupo te plantearías darle una oportunidad aunque no encaje con lo que buscas?',
 '¿Quién crees que podría despertar en ti más interés del que admitirías?',
 '¿Con quién del grupo crees que tendrías una relación más intensa pero menos estable?',
 '¿Quién del grupo te parece más probable que te descoloque emocionalmente?',
 '¿A quién del grupo te daría más miedo empezar a conocer en serio?',
 '¿Quién crees que podría convertir una amistad tranquila en algo complicado?',
 '¿Con quién del grupo tendrías más posibilidades de acabar teniendo una conversación que cambie vuestra relación?',
 '¿Quién te parece más probable que te atraiga por cómo piensa?',
 '¿A quién del grupo te daría más curiosidad ver completamente arreglado/a para una cita?',
 '¿Quién crees que podría gustarte más después de escucharle hablar durante horas?',
 '¿Con quién del grupo tendrías más posibilidades de acabar teniendo una historia que no esperabas?',
 '¿Quién te parece más probable que haga que te arrepientas de haber empezado a hablar por privado?',
 '¿A quién del grupo te daría más rabia descubrir que le gusta otra persona?',
 '¿Quién crees que podría hacer que te plantearas una relación a distancia?',
 '¿Con quién del grupo tendrías más riesgo de mezclar sexo y sentimientos?',
 '¿Quién te parece más probable que te haga perder objetividad?',
 '¿A quién del grupo te costaría más dejar de mirar si estuviera delante de ti?',
 '¿Quién crees que podría hacerte sentir inseguro/a sin proponérselo?',
 '¿Con quién del grupo te parecería más fácil tener una conversación subida de tono?',
 '¿Quién te parece más probable que te atraiga más por voz que por fotos?',
 '¿A quién del grupo te costaría más sacar de tu cabeza después de un beso?',
 '¿Quién crees que podría hacerte olvidar durante un rato a alguien que todavía te importa?',
 '¿Con quién del grupo tendrías más posibilidades de arrepentirte de no haber intentado algo?',
 '¿Quién te parece más probable que te haga cruzar una línea que normalmente no cruzarías?',
 '¿A quién del grupo te daría más curiosidad conocer estando ambos completamente solteros?',
 '¿Quién crees que podría gustarte en el peor momento posible?',
 '¿Con quién del grupo te costaría más separar deseo de sentimientos?',
 '¿Quién te parece más probable que te haga pensar demasiado después de una conversación privada?',
 '¿A quién del grupo te daría más curiosidad ver en una cita real?',
 '¿Quién crees que podría hacerte sentir química simplemente por cómo escribe?',
 '¿Con quién del grupo te sentirías más incómodo/a si supieras que le gustas?',
 '¿Quién te parece más probable que te atraiga precisamente porque no te conviene?',
 '¿A quién del grupo te plantearías besar aunque supieras que luego se comentaría durante semanas?',
 '¿Quién crees que podría hacerte cambiar tus reglas sobre con quién te meterías?',
 '¿Con quién del grupo te parecería más difícil mantener distancia emocional?',
 '¿Quién te parece más probable que te saque de tu zona de confort sentimental?',
 '¿A quién del grupo te costaría más decirle que solo quieres amistad?',
 '¿Quién crees que podría hacerte sentir algo aunque intentaras evitarlo?',
 '¿Con quién del grupo te parecería más probable acabar en una historia secreta?',
 '¿Quién te parece más probable que te haga replantearte una relación actual o pasada?',
 '¿A quién del grupo te daría más curiosidad saber si alguna vez se ha fijado en ti?',
 '¿Quién crees que podría hacerte sentir atraído/a sin haberlo buscado?',
 '¿Con quién del grupo crees que podrías tener una conexión muy buena pero una relación desastrosa?',
 "¿Quién te parece más probable que te haga pensar 'esto es una mala idea' y aun así seguir?",
 '¿A quién del grupo te costaría más ver como solo un amigo/a después de una noche juntos?',
 '¿Quién crees que podría despertar en ti el tipo de atracción que más problemas te da?']

BOMBA = ['Si tuvieras que acostarte con una persona del grupo, ¿a quién elegirías?',
 'Si tuvieras que besar a dos personas del grupo esta noche, ¿quiénes serían?',
 '¿Con quién del grupo tendrías sexo y con quién jamás aunque fueras la última persona del planeta?',
 '¿Quién del grupo crees que te atraería más si lo tuvieras delante ahora mismo?',
 'Si mañana despertaras en la cama con alguien del grupo, ¿con quién preferirías que fuera?',
 "¿A quién del grupo mandarías un mensaje de 'ven' a las tres de la mañana?",
 '¿Quién del grupo crees que tendría más posibilidades de hacerte ser infiel?',
 '¿Con quién del grupo tendrías una aventura que nadie pudiera descubrir?',
 '¿Quién del grupo crees que podría hacerte olvidar a alguien que todavía te importa?',
 '¿A quién del grupo le aceptarías una proposición indecente sin pensarlo demasiado?',
 'Si tuvieras que elegir pareja dentro del grupo durante un año entero, ¿a quién elegirías?',
 '¿A quién del grupo elegirías para una noche y a quién para una relación?',
 '¿Quién del grupo te parece demasiado atractivo/a como para ser buena idea?',
 '¿Quién crees que podría acabar siendo tu peor decisión sentimental?',
 '¿Con quién del grupo crees que habría más tensión sexual si os vierais en persona?',
 'Si pudieras leer un solo chat privado de alguien del grupo, ¿de quién sería?',
 '¿A quién del grupo jamás le dejarías leer tus conversaciones privadas?',
 'Si supieras que alguien del grupo está pillado por ti, ¿quién te gustaría que fuera?',
 '¿Quién del grupo te dolería más descubrir que habla mal de ti por privado?',
 '¿A quién del grupo eliminarías definitivamente si tuvieras que elegir a una persona?',
 '¿Quién del grupo crees que esconde la opinión más fuerte sobre otra persona del grupo?',
 'Di una persona del grupo con la que tendrías algo y una con la que ni de coña.',
 '¿Quién del grupo crees que tiene más posibilidades de acabar teniendo sexo con otra persona del grupo?',
 "¿Quién del grupo sería tu elección si te dijeran: 'o te lías con esta persona o abandonas el grupo'?",
 'Si esta noche hubiera una fiesta privada solo con gente del grupo, ¿con quién crees que acabarías tonteando?',
 'Si tuvieras que mandar una foto provocativa a alguien del grupo, ¿a quién sería?',
 '¿Con quién del grupo aceptarías compartir habitación en una escapada sabiendo que solo hay una cama?',
 'Si tuvieras que elegir a alguien del grupo para darte un beso de diez segundos, ¿quién sería?',
 '¿A quién del grupo besarías aunque supieras que luego se iba a montar un drama enorme?',
 '¿Con quién del grupo crees que tendrías más riesgo de engancharte después de una sola noche?',
 '¿Quién del grupo crees que podría romperte el corazón de verdad?',
 '¿A quién del grupo llamarías si estuvieras emocionalmente débil y quisieras cometer una mala decisión?',
 '¿Quién crees que podría hacerte traicionar una regla que juraste no romper?',
 '¿Con quién del grupo te meterías en un lío aunque supieras que acabaría mal?',
 '¿Quién del grupo te pondría más nervioso/a si te confesara que le gustas?',
 'Si tuvieras que tener una cita secreta con alguien del grupo, ¿a quién elegirías?',
 '¿Quién del grupo crees que podría acabar gustándote demasiado si empezaras a hablar mucho por privado?',
 '¿Quién te parece la persona del grupo con más posibilidades de ser tu debilidad?',
 '¿A quién del grupo no deberías besar porque sabes que te complicaría la vida?',
 '¿Con quién del grupo crees que sería más difícil mantenerlo solo en algo físico?',
 'Si solo pudieras hablar por privado con una persona del grupo durante un mes, ¿a quién elegirías?',
 '¿A quién del grupo le confiarías una confesión que podría cambiar la opinión que tiene de ti?',
 '¿Quién del grupo crees que podría hacerte sentir celos aunque no fuerais nada?',
 'Si tuvieras que borrar para siempre a una persona del grupo y acercarte mucho más a otra, ¿quiénes serían?',
 '¿Quién del grupo crees que tiene más posibilidades de haber mentido sobre quién le gusta?',
 '¿Quién del grupo crees que podría estar sintiendo algo por alguien y fingiendo que no?',
 '¿A quién del grupo te daría más vergüenza admitir que te atrae?',
 '¿Con quién del grupo tendrías una cita aunque supieras que alguien se iba a enfadar?',
 '¿Quién del grupo crees que podría hacerte caer en una relación que sabes que no te conviene?',
 '¿A quién del grupo elegirías para un beso, a quién para una noche y a quién para una relación?',
 '¿Quién del grupo sería tu mayor tentación si estuvieras soltero/a y todos estuvieran disponibles?',
 "¿A quién del grupo te gustaría escuchar decirte claramente 'me gustas'?",
 '¿Quién crees que tendría más poder sobre ti si empezaras a sentir algo?',
 '¿A quién del grupo besarías delante de todos solo por ver qué pasa?',
 'Si tuvieras que elegir a alguien del grupo para una noche sin consecuencias, ¿quién sería?',
 '¿Quién del grupo crees que podría hacerte actuar de una forma que normalmente no harías?',
 '¿A quién del grupo te dolería más ver enamorándose de otra persona?',
 '¿Quién del grupo crees que podría convertirse en tu problema favorito?',
 'Si tuvieras que confesar una atracción por alguien del grupo ahora mismo, ¿a quién nombrarías?',
 '¿Quién del grupo crees que sería la peor persona de la que podrías enamorarte?',
 '¿Con quién del grupo aceptarías una escapada de 48 horas sin contarle a nadie dónde vais?',
 '¿A quién del grupo dejarías acercarse demasiado sabiendo que probablemente acabarías pillándote?',
 "¿Quién del grupo crees que podría hacerte romper tu propio 'tipo' completamente?",
 'Si pudieras saber quién ha fantaseado contigo dentro del grupo, ¿de quién te gustaría descubrirlo?',
 '¿Con quién del grupo crees que habría más posibilidades de acabar haciendo algo que luego negaríais?',
 "¿A quién del grupo le mandarías un '¿estás despierto/a?' sabiendo exactamente lo que significa?",
 '¿Quién del grupo crees que sería capaz de hacerte sentir mariposas y ansiedad al mismo tiempo?',
 '¿A quién del grupo elegirías si tuvieras que pasar una noche entera hablando a solas, sin móviles ni escapatoria?',
 '¿Quién del grupo crees que sería la persona más peligrosa para ti si hubiera atracción mutua?',
 '¿A quién del grupo no invitarías jamás a conocer a tu pareja por miedo a que hubiera química?',
 'Si tuvieras que admitir que alguien del grupo te parece irresistible, ¿quién sería?',
 '¿Quién del grupo crees que podría hacerte caer aunque al principio no te gustara nada?',
 "¿A quién del grupo te costaría más decirle 'esto no puede seguir'?",
 '¿Quién del grupo crees que podría hacerte olvidar una promesa que te hiciste a ti mismo/a?',
 '¿Con quién del grupo crees que una amistad tendría más riesgo de convertirse en otra cosa?',
 '¿Quién del grupo te parece más probable que termine siendo un secreto que no contarías a nadie?',
 'Si tuvieras que elegir a una persona para que te bese y otra para que te rechace, ¿quiénes serían?',
 '¿Quién del grupo crees que podría sacar tu lado más celoso/a?',
 '¿A quién del grupo le permitirías acercarse a ti aunque supieras que es una pésima idea?',
 '¿Quién del grupo sería la persona que más te costaría sacar de tu cabeza después de una noche juntos?',
 'Si tuvieras que elegir a alguien del grupo para que te rompiera el corazón, ¿a quién preferirías?',
 'Si pudieras besar a una persona del grupo sin que nadie se enterara jamás, ¿quién sería?',
 '¿A quién del grupo elegirías para una noche sabiendo que después tendríais que seguir hablando aquí como si nada?',
 'Si tuvieras que confesar ahora mismo una fantasía relacionada con alguien del grupo, ¿a quién nombrarías?',
 '¿Quién del grupo crees que podría hacerte perder más el control si hubiera atracción mutua?',
 'Si tuvieras que pasar un fin de semana entero a solas con alguien del grupo, ¿a quién elegirías?',
 '¿A quién del grupo preferirías descubrir esperándote en la puerta de tu casa esta noche?',
 'Si solo pudieras besar a una persona del grupo durante todo un año, ¿quién sería?',
 '¿Quién del grupo crees que podría hacerte cometer la peor decisión sentimental de tu vida?',
 'Si tuvieras que elegir a alguien del grupo para compartir cama una noche, ¿quién sería?',
 '¿A quién del grupo aceptarías ver en secreto aunque supieras que no debería pasar?',
 'Si tuvieras que admitir que alguien del grupo te pone nervioso/a de una forma especial, ¿quién sería?',
 '¿Quién del grupo te parecería más peligroso si supieras que también siente atracción por ti?',
 "Si una persona del grupo te dijera 'bésame ahora', ¿de quién te costaría más decir que no?",
 '¿A quién del grupo elegirías para vivir una historia intensa aunque durara solo un mes?',
 'Si pudieras saber exactamente qué piensa una persona del grupo cuando te lee, ¿a quién elegirías?',
 '¿Quién del grupo crees que podría convertirse más fácilmente en una obsesión temporal para ti?',
 'Si tuvieras que tener una cita nocturna con alguien del grupo y no pudieras cancelar, ¿a quién escogerías?',
 '¿A quién del grupo besarías aunque supieras que alguien cercano se iba a enterar?',
 'Si tuvieras que elegir a una persona del grupo para tener una conversación completamente sincera sobre sexo, ¿quién '
 'sería?',
 '¿Quién del grupo te parecería más difícil de rechazar si se presentara delante de ti con intención clara?',
 'Si tuvieras que elegir entre besar a alguien que te gusta o acostarte con alguien que te atrae, ¿qué dos personas '
 'del grupo serían?',
 '¿A quién del grupo te daría más miedo gustarle de verdad?',
 'Si te dijeran que una persona del grupo sueña contigo, ¿quién esperarías que fuera?',
 '¿Quién del grupo crees que podría hacer que escondieras una historia al resto?',
 'Si tuvieras que pasar una noche entera sin poder apartarte de una persona del grupo, ¿a quién elegirías?',
 '¿A quién del grupo le permitirías acercarse demasiado aunque supieras que te complicaría la vida?',
 'Si solo pudieras enviar un mensaje privado esta noche a una persona del grupo, ¿a quién sería?',
 '¿Quién del grupo crees que podría hacerte dudar de una relación estable?',
 'Si tuvieras que elegir a alguien del grupo para vivir una aventura secreta durante un mes, ¿quién sería?',
 '¿A quién del grupo te gustaría descubrir mirándote con intención en una quedada?',
 '¿Quién del grupo crees que podría hacerte olvidar tus límites por una noche?',
 'Si tuvieras que besar a alguien del grupo delante de todos, ¿a quién elegirías para provocar más impacto?',
 '¿A quién del grupo preferirías tener demasiado cerca después de unas copas?',
 'Si tuvieras que elegir a una persona del grupo para que fuera tu ex, ¿quién sería?',
 '¿Quién del grupo crees que podría convertirse en alguien que te costara mucho superar?',
 'Si pudieras tener una única noche con alguien del grupo sin consecuencias, ¿a quién escogerías?',
 '¿A quién del grupo elegirías para una relación intensa aunque supieras que acabaría mal?',
 '¿Quién del grupo te parecería más peligroso si empezara a escribirte todos los días?',
 'Si tuvieras que compartir un secreto sexual con una persona del grupo, ¿a quién se lo contarías?',
 '¿A quién del grupo besarías si supieras que después no podríais volver a fingir que sois solo amigos?',
 'Si una persona del grupo pudiera escuchar todos tus pensamientos sobre ella durante un minuto, ¿quién te daría más '
 'miedo que fuera?',
 '¿Quién del grupo crees que podría hacerte sentir más celos si empezara algo con otra persona de aquí?',
 'Si tuvieras que elegir a alguien del grupo para una cita que acabara sí o sí en beso, ¿quién sería?',
 '¿A quién del grupo te gustaría ver reaccionar si le dijeras que te atrae?',
 '¿Quién del grupo crees que podría hacerte mentir diciendo que no te importa cuando sí te importa?',
 'Si tuvieras que compartir habitación en un hotel con alguien del grupo durante tres noches, ¿a quién elegirías?',
 '¿A quién del grupo te gustaría tener muy cerca en una fiesta donde nadie os conociera?',
 '¿Quién del grupo crees que podría hacerte querer más de lo que habías planeado?',
 'Si tuvieras que admitir una debilidad por alguien del grupo, ¿quién sería?',
 '¿A quién del grupo elegirías para una historia que jamás contarías completa?',
 '¿Quién del grupo crees que podría hacerte sentir más vulnerable después de una noche juntos?',
 'Si te obligaran a elegir una persona del grupo para besar cada vez que os vierais, ¿quién sería?',
 '¿A quién del grupo te costaría más mirar a la cara después de una noche de tensión?',
 '¿Quién del grupo crees que podría hacerte pensar seriamente en romper una regla importante?',
 'Si tuvieras que elegir a alguien del grupo para ser tu tentación prohibida, ¿quién sería?',
 '¿A quién del grupo aceptarías ver a solas aunque supieras que podría pasar algo?',
 '¿Quién del grupo crees que podría meterse más rápido en tu cabeza y quedarse ahí?',
 'Si tuvieras que elegir a una persona del grupo para una relación sin etiquetas, ¿quién sería?',
 '¿A quién del grupo te gustaría que te confesara una atracción inesperada?',
 '¿Quién del grupo crees que podría hacerte sentir más inseguro/a si empezaras a enamorarte?',
 'Si tuvieras que elegir entre una noche perfecta y una relación complicada con alguien del grupo, ¿a quién pondrías '
 'en cada opción?',
 '¿A quién del grupo besarías si supieras que después se convertiría en tema de conversación durante meses?',
 '¿Quién del grupo crees que podría hacer que sintieras algo demasiado fuerte demasiado rápido?',
 'Si tuvieras que elegir a alguien del grupo para compartir un secreto que no sabe nadie más, ¿quién sería?',
 '¿A quién del grupo preferirías tener como amor imposible?',
 '¿Quién del grupo crees que podría hacerte volver a caer aunque ya hubieras decidido alejarte?',
 'Si solo pudieras tener una conversación completamente íntima con una persona del grupo, ¿a quién elegirías?',
 '¿A quién del grupo te daría más miedo besar porque sabes que podría gustarte demasiado?',
 '¿Quién del grupo crees que podría convertirse en tu mayor debilidad si os conocierais mejor?']

CATEGORIAS = {
    "🟡 SALSEO": SALSEO,
    "🔴 SIN FILTRO": SIN_FILTRO,
    "💣 BOMBA": BOMBA,
}

PESOS = {
    "🟡 SALSEO": 25,
    "🔴 SIN FILTRO": 45,
    "💣 BOMBA": 30,
}

def _elegir_categoria():
    categorias = list(CATEGORIAS.keys())
    pesos = [PESOS[c] for c in categorias]
    return random.choices(categorias, weights=pesos, k=1)[0]

def _elegir_pregunta(context):
    categoria = _elegir_categoria()

    usadas_por_categoria = context.chat_data.setdefault(
        "dadonet_usadas",
        {nombre: [] for nombre in CATEGORIAS}
    )

    usadas = usadas_por_categoria.setdefault(categoria, [])
    disponibles = [p for p in CATEGORIAS[categoria] if p not in usadas]

    # Una pregunta solo puede repetirse después de agotar las 150 de su categoría.
    if not disponibles:
        usadas.clear()
        disponibles = CATEGORIAS[categoria][:]

    pregunta = random.choice(disponibles)
    usadas.append(pregunta)

    return categoria, pregunta

async def dadonet(update, context):
    categoria, pregunta = _elegir_pregunta(context)

    texto = (
        f"🎲 DADONET\n\n"
        f"{categoria}\n\n"
        f"{pregunta}\n\n"
        f"🎲 1–3 → Elige quién responde 😈\n"
        f"🎲 4–6 → Te toca responder a ti ☠️"
    )

    await update.message.reply_text(texto)
