import random

# DADONET 2.0 — 500 preguntas
# 440 preguntas centradas en interacción/salseo/conflictos/confesiones.
# Solo 60 (12 %) son de atracción o ligoteo.
# Además evita sacar el mismo tema en las 3 tiradas siguientes.
#
# IMPORTANTE: context.chat_data no sobrevive a un reinicio de Railway
# si el bot no tiene persistencia configurada.

PREGUNTAS = [{'tema': 'PERCEPCION',
  'nivel': '🟡 SALSEO',
  'pregunta': '¿De quién del grupo te gustaría saber qué piensa realmente de ti?'},
 {'tema': 'PERCEPCION',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Quién crees que tiene una opinión de ti muy distinta a la que muestra?'},
 {'tema': 'PERCEPCION', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién crees que te ha juzgado demasiado rápido?'},
 {'tema': 'PERCEPCION', 'nivel': '💣 BOMBA', 'pregunta': '¿De quién te sorprendería más descubrir que no le caes bien?'},
 {'tema': 'PERCEPCION', 'nivel': '🟡 SALSEO', 'pregunta': '¿Quién crees que ha cambiado más su opinión sobre ti?'},
 {'tema': 'PERCEPCION', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿A quién crees que tú has juzgado demasiado pronto?'},
 {'tema': 'PERCEPCION', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién crees que te entiende mejor de lo que aparenta?'},
 {'tema': 'PERCEPCION', 'nivel': '💣 BOMBA', 'pregunta': '¿Quién crees que interpreta peor tu forma de ser?'},
 {'tema': 'PERCEPCION',
  'nivel': '🟡 SALSEO',
  'pregunta': '¿De quién querrías escuchar una descripción totalmente sincera sobre ti?'},
 {'tema': 'PERCEPCION',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Quién crees que te tiene más calado/a de lo que te gustaría?'},
 {'tema': 'PERCEPCION', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién todavía no ha entendido bien cómo eres?'},
 {'tema': 'PERCEPCION',
  'nivel': '💣 BOMBA',
  'pregunta': '¿Quién crees que podría decirte una verdad sobre ti que te dolería?'},
 {'tema': 'PERCEPCION',
  'nivel': '🟡 SALSEO',
  'pregunta': '¿Quién te defendería si alguien hablara mal de ti y tú no estuvieras?'},
 {'tema': 'PERCEPCION',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Quién crees que probablemente te ha criticado alguna vez por privado?'},
 {'tema': 'PERCEPCION', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Sobre quién has cambiado más de opinión para bien?'},
 {'tema': 'PERCEPCION', 'nivel': '💣 BOMBA', 'pregunta': '¿Sobre quién has cambiado más de opinión para mal?'},
 {'tema': 'PERCEPCION',
  'nivel': '🟡 SALSEO',
  'pregunta': '¿Quién crees que es más diferente en privado que en el grupo?'},
 {'tema': 'PERCEPCION',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Quién proyecta una imagen que no coincide del todo con cómo es?'},
 {'tema': 'PERCEPCION',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Quién parece más seguro/a de lo que realmente se siente?'},
 {'tema': 'PERCEPCION', 'nivel': '💣 BOMBA', 'pregunta': '¿Quién parece más frío/a de lo que realmente es?'},
 {'tema': 'PERCEPCION', 'nivel': '🟡 SALSEO', 'pregunta': '¿Quién parece más inocente de lo que realmente es?'},
 {'tema': 'PERCEPCION', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién guarda más opiniones de las que dice?'},
 {'tema': 'PERCEPCION', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién crees que se arrepiente más de lo que escribe?'},
 {'tema': 'PERCEPCION',
  'nivel': '💣 BOMBA',
  'pregunta': '¿Quién podría sorprenderte más si contara lo que piensa de todos?'},
 {'tema': 'PERCEPCION', 'nivel': '🟡 SALSEO', 'pregunta': '¿Quién crees que se preocupa más por cómo lo ve el grupo?'},
 {'tema': 'PERCEPCION', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién crees que conoce peor la imagen que proyecta?'},
 {'tema': 'PERCEPCION',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Quién crees que te considera más complicado/a de lo que eres?'},
 {'tema': 'PERCEPCION',
  'nivel': '💣 BOMBA',
  'pregunta': '¿Quién crees que piensa que eres más sensible de lo que aparentas?'},
 {'tema': 'PERCEPCION', 'nivel': '🟡 SALSEO', 'pregunta': '¿Quién crees que piensa que eres más borde de lo que eres?'},
 {'tema': 'PERCEPCION',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Quién crees que tiene más prejuicios sobre otros miembros?'},
 {'tema': 'PERCEPCION', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién crees que es más difícil de conocer de verdad?'},
 {'tema': 'PERCEPCION', 'nivel': '💣 BOMBA', 'pregunta': '¿Quién crees que se toma más cosas personalmente?'},
 {'tema': 'PERCEPCION', 'nivel': '🟡 SALSEO', 'pregunta': '¿Quién crees que perdona pero no olvida?'},
 {'tema': 'PERCEPCION',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Quién crees que te conoce mejor sin haber hablado mucho contigo?'},
 {'tema': 'PERCEPCION', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién crees que ha entendido peor alguna broma tuya?'},
 {'tema': 'PERCEPCION',
  'nivel': '💣 BOMBA',
  'pregunta': '¿Quién crees que tiene una primera impresión tuya que ya debería actualizar?'},
 {'tema': 'PERCEPCION',
  'nivel': '🟡 SALSEO',
  'pregunta': '¿Quién sería más sincero/a si le preguntaras qué defecto ve en ti?'},
 {'tema': 'PERCEPCION', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién crees que ve una faceta tuya que el resto no ve?'},
 {'tema': 'PERCEPCION', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién crees que se equivoca más contigo?'},
 {'tema': 'PERCEPCION',
  'nivel': '💣 BOMBA',
  'pregunta': '¿De quién te interesa más saber si su opinión sobre ti es buena o mala?'},
 {'tema': 'PRIVADOS',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Si pudieras leer cinco minutos de un privado entre dos miembros, ¿qué dos elegirías?'},
 {'tema': 'PRIVADOS', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién crees que sabe más secretos del grupo?'},
 {'tema': 'PRIVADOS', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿A quién confiarías un secreto serio sin dudar?'},
 {'tema': 'PRIVADOS', 'nivel': '💣 BOMBA', 'pregunta': '¿A quién no le contarías algo delicado ni bajo amenaza?'},
 {'tema': 'PRIVADOS', 'nivel': '🟡 SALSEO', 'pregunta': '¿Quién crees que hace más capturas de conversaciones?'},
 {'tema': 'PRIVADOS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Quién crees que ha enviado alguna captura del grupo fuera?'},
 {'tema': 'PRIVADOS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Quién crees que habla más por privado de lo que ocurre aquí?'},
 {'tema': 'PRIVADOS',
  'nivel': '💣 BOMBA',
  'pregunta': '¿Quién crees que tiene más privados abiertos con gente del grupo?'},
 {'tema': 'PRIVADOS', 'nivel': '🟡 SALSEO', 'pregunta': '¿Quién recibe más mensajes después de un drama?'},
 {'tema': 'PRIVADOS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Quién pregunta por privado lo que no se atreve a preguntar aquí?'},
 {'tema': 'PRIVADOS', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién sería incapaz de guardar un secreto jugoso?'},
 {'tema': 'PRIVADOS', 'nivel': '💣 BOMBA', 'pregunta': '¿Quién conoce mejor todos los cotilleos?'},
 {'tema': 'PRIVADOS',
  'nivel': '🟡 SALSEO',
  'pregunta': '¿Entre qué dos miembros te daría más curiosidad leer una conversación?'},
 {'tema': 'PRIVADOS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Quién podría escribir un libro con todo lo que sabe del grupo?'},
 {'tema': 'PRIVADOS', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién crees que ha pedido opinión sobre ti por privado?'},
 {'tema': 'PRIVADOS',
  'nivel': '💣 BOMBA',
  'pregunta': '¿A quién preguntarías si quisieras saber qué se está cociendo de verdad?'},
 {'tema': 'PRIVADOS', 'nivel': '🟡 SALSEO', 'pregunta': '¿Quién tiene más información comprometida sobre los demás?'},
 {'tema': 'PRIVADOS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Quién sería peor guardando una confidencia si se enfadara contigo?'},
 {'tema': 'PRIVADOS', 'nivel': '🔴 SIN FILTRO', 'pregunta': "¿Quién utiliza más el 'te cuento pero no digas nada'?"},
 {'tema': 'PRIVADOS',
  'nivel': '💣 BOMBA',
  'pregunta': '¿Quién ha enseñado alguna vez un mensaje para demostrar que tenía razón?'},
 {'tema': 'PRIVADOS',
  'nivel': '🟡 SALSEO',
  'pregunta': '¿Quién podría sonsacarte información sin que te dieras cuenta?'},
 {'tema': 'PRIVADOS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Quién escucha un cotilleo y necesita contárselo a alguien?'},
 {'tema': 'PRIVADOS', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién podría guardar el secreto más gordo durante años?'},
 {'tema': 'PRIVADOS',
  'nivel': '💣 BOMBA',
  'pregunta': '¿Quién crees que sabe quién se lleva realmente bien y quién solo se tolera?'},
 {'tema': 'PRIVADOS',
  'nivel': '🟡 SALSEO',
  'pregunta': '¿Quién sería más peligroso/a con acceso a todos los privados diez minutos?'},
 {'tema': 'PRIVADOS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Quién descubriría más cosas revisando los chats de los demás?'},
 {'tema': 'PRIVADOS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Quién crees que podría tener un secreto compartido con alguien del grupo?'},
 {'tema': 'PRIVADOS',
  'nivel': '💣 BOMBA',
  'pregunta': '¿Qué conversación privada tuya con alguien de aquí te daría más apuro que se leyera?'},
 {'tema': 'PRIVADOS',
  'nivel': '🟡 SALSEO',
  'pregunta': '¿Quién crees que pregunta a terceros antes de enfrentarse directamente a alguien?'},
 {'tema': 'PRIVADOS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Quién crees que ha hablado de alguien del grupo con gente de fuera?'},
 {'tema': 'PRIVADOS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Quién podría reconstruir mejor todos los dramas que han pasado?'},
 {'tema': 'PRIVADOS',
  'nivel': '💣 BOMBA',
  'pregunta': "¿Quién crees que ha preguntado alguna vez '¿qué opinas de X?' por privado?"},
 {'tema': 'PRIVADOS', 'nivel': '🟡 SALSEO', 'pregunta': '¿Quién crees que guarda más capturas antiguas?'},
 {'tema': 'PRIVADOS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Quién crees que tiene más información que no debería saber?'},
 {'tema': 'PRIVADOS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Quién sería la peor persona a la que enviar por error una captura comprometida?'},
 {'tema': 'PRIVADOS',
  'nivel': '💣 BOMBA',
  'pregunta': '¿Quién crees que ha tenido un privado incómodo con otro miembro sin que nadie se enterara?'},
 {'tema': 'PRIVADOS',
  'nivel': '🟡 SALSEO',
  'pregunta': '¿Quién crees que sabe algo de ti que tú no recuerdas haber contado?'},
 {'tema': 'PRIVADOS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Quién crees que sería el primero en enterarse de un cotilleo nuevo?'},
 {'tema': 'PRIVADOS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Quién crees que ha borrado una conversación para evitar problemas?'},
 {'tema': 'PRIVADOS',
  'nivel': '💣 BOMBA',
  'pregunta': '¿A quién le confiarías el móvil desbloqueado durante diez minutos?'},
 {'tema': 'CONFLICTO', 'nivel': '🟡 SALSEO', 'pregunta': '¿Con quién acabarías teniendo la discusión más fuerte?'},
 {'tema': 'CONFLICTO', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién tiene peor perder una discusión?'},
 {'tema': 'CONFLICTO', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién necesita tener la última palabra?'},
 {'tema': 'CONFLICTO', 'nivel': '💣 BOMBA', 'pregunta': '¿Quién se ofende con más facilidad?'},
 {'tema': 'CONFLICTO', 'nivel': '🟡 SALSEO', 'pregunta': '¿Quién provoca y después dice que solo bromeaba?'},
 {'tema': 'CONFLICTO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Quién sabe exactamente dónde tocar para picar a alguien?'},
 {'tema': 'CONFLICTO', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién podría enfadarse contigo por esta respuesta?'},
 {'tema': 'CONFLICTO', 'nivel': '💣 BOMBA', 'pregunta': '¿Quién sería más difícil de reconciliar después de una pelea?'},
 {'tema': 'CONFLICTO', 'nivel': '🟡 SALSEO', 'pregunta': '¿Quién guarda rencor durante más tiempo?'},
 {'tema': 'CONFLICTO', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién discutiría incluso sabiendo que no tiene razón?'},
 {'tema': 'CONFLICTO', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién reconoce peor cuando se equivoca?'},
 {'tema': 'CONFLICTO', 'nivel': '💣 BOMBA', 'pregunta': '¿Quién pediría perdón primero después de una bronca?'},
 {'tema': 'CONFLICTO', 'nivel': '🟡 SALSEO', 'pregunta': '¿Quién nunca pediría perdón aunque supiera que debería?'},
 {'tema': 'CONFLICTO', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién abandonaría el grupo por un calentón?'},
 {'tema': 'CONFLICTO', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién volvería poco después de irse enfadado/a?'},
 {'tema': 'CONFLICTO',
  'nivel': '💣 BOMBA',
  'pregunta': '¿Quién monta más películas en su cabeza antes de preguntar qué pasó?'},
 {'tema': 'CONFLICTO',
  'nivel': '🟡 SALSEO',
  'pregunta': '¿Quién interpreta más fácilmente un silencio como algo personal?'},
 {'tema': 'CONFLICTO', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Con quién sería más difícil convivir una semana?'},
 {'tema': 'CONFLICTO', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién disfruta secretamente cuando hay salseo?'},
 {'tema': 'CONFLICTO', 'nivel': '💣 BOMBA', 'pregunta': '¿Quién sería mejor mediador/a en una pelea?'},
 {'tema': 'CONFLICTO', 'nivel': '🟡 SALSEO', 'pregunta': '¿Quién empeoraría una pelea intentando mediar?'},
 {'tema': 'CONFLICTO', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién sería más duro/a diciendo una verdad incómoda?'},
 {'tema': 'CONFLICTO', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién usa más la ironía cuando está molesto/a?'},
 {'tema': 'CONFLICTO', 'nivel': '💣 BOMBA', 'pregunta': "¿Quién dice 'me da igual' cuando claramente no le da igual?"},
 {'tema': 'CONFLICTO', 'nivel': '🟡 SALSEO', 'pregunta': '¿Quién se calla hasta que explota?'},
 {'tema': 'CONFLICTO', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién explota primero y piensa después?'},
 {'tema': 'CONFLICTO', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién bloquearía a alguien por una discusión?'},
 {'tema': 'CONFLICTO', 'nivel': '💣 BOMBA', 'pregunta': '¿Quién desbloquearía primero por curiosidad?'},
 {'tema': 'CONFLICTO',
  'nivel': '🟡 SALSEO',
  'pregunta': '¿Quién tiene más facilidad para hacer sentir culpable a alguien?'},
 {'tema': 'CONFLICTO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Quién llevaría peor descubrir un grupo paralelo sin él/ella?'},
 {'tema': 'CONFLICTO', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién se tomaría demasiado en serio una broma?'},
 {'tema': 'CONFLICTO', 'nivel': '💣 BOMBA', 'pregunta': '¿Quién se atrevería a decir lo que varios piensan?'},
 {'tema': 'CONFLICTO',
  'nivel': '🟡 SALSEO',
  'pregunta': '¿Quién cambiaría menos de opinión aunque todos estuvieran en contra?'},
 {'tema': 'CONFLICTO', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién podría acabar discutiendo con La Patrona? 😂'},
 {'tema': 'CONFLICTO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': "¿A quién dirías 'te quiero mucho, pero discutir contigo es imposible'?"},
 {'tema': 'CONFLICTO',
  'nivel': '💣 BOMBA',
  'pregunta': '¿Con quién tienes una pequeña tensión que nunca habéis hablado?'},
 {'tema': 'CONFLICTO',
  'nivel': '🟡 SALSEO',
  'pregunta': '¿Quién crees que confunde más fácilmente sinceridad con brusquedad?'},
 {'tema': 'CONFLICTO', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién se pondría más a la defensiva ante una crítica?'},
 {'tema': 'CONFLICTO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Quién podría convertir una tontería en un problema serio?'},
 {'tema': 'CONFLICTO', 'nivel': '💣 BOMBA', 'pregunta': '¿Quién crees que sabe discutir mejor sin perder los papeles?'},
 {'tema': 'ELECCIONES',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Si tuvieras que convivir un mes con dos personas, ¿a quiénes eliges?'},
 {'tema': 'ELECCIONES',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si tuvieras que irte de viaje mañana con alguien, ¿a quién escogerías?'},
 {'tema': 'ELECCIONES',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si necesitaras que alguien te recogiera a las cuatro de la mañana, ¿a quién llamarías?'},
 {'tema': 'ELECCIONES',
  'nivel': '💣 BOMBA',
  'pregunta': 'Si tuvieras un problema serio, ¿a quién pedirías consejo primero?'},
 {'tema': 'ELECCIONES',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Si necesitaras que alguien mintiera por ti, ¿a quién elegirías?'},
 {'tema': 'ELECCIONES',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si tuvieras que montar un negocio con alguien, ¿con quién sería?'},
 {'tema': 'ELECCIONES',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si tuvieras que compartir piso con alguien, ¿quién sería la opción menos mala?'},
 {'tema': 'ELECCIONES',
  'nivel': '💣 BOMBA',
  'pregunta': 'Si tuvieras que dejar las llaves de tu casa a alguien, ¿a quién?'},
 {'tema': 'ELECCIONES', 'nivel': '🟡 SALSEO', 'pregunta': 'Si tuvieras que confiar dinero a alguien, ¿quién sería?'},
 {'tema': 'ELECCIONES',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si necesitaras que alguien te defendiera en una discusión, ¿a quién elegirías?'},
 {'tema': 'ELECCIONES',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si estuvieras encerrado/a 24 horas con alguien, ¿quién te aburriría menos?'},
 {'tema': 'ELECCIONES',
  'nivel': '💣 BOMBA',
  'pregunta': 'Si solo pudieras conservar contacto con tres personas, ¿quiénes serían?'},
 {'tema': 'ELECCIONES',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Si tuvieras que expulsar a alguien durante una semana, ¿a quién mandarías de vacaciones?'},
 {'tema': 'ELECCIONES',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si intercambiaras tu Telegram un día con alguien, ¿con quién te daría menos miedo?'},
 {'tema': 'ELECCIONES',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Quién podría responder mejor DadoNet haciéndose pasar por ti?'},
 {'tema': 'ELECCIONES', 'nivel': '💣 BOMBA', 'pregunta': 'Si necesitaras una coartada creíble, ¿a quién llamarías?'},
 {'tema': 'ELECCIONES',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Si participaras en un concurso por parejas, ¿a quién elegirías?'},
 {'tema': 'ELECCIONES', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Con quién harías un viaje de diez horas en coche?'},
 {'tema': 'ELECCIONES', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿A quién confiarías organizarte una cita a ciegas?'},
 {'tema': 'ELECCIONES', 'nivel': '💣 BOMBA', 'pregunta': '¿A quién pondrías de administrador/a del grupo una semana?'},
 {'tema': 'ELECCIONES', 'nivel': '🟡 SALSEO', 'pregunta': '¿A quién pedirías 500 euros si no tuvieras otra opción?'},
 {'tema': 'ELECCIONES', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién elegiría mejor una foto de perfil para ti?'},
 {'tema': 'ELECCIONES', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿A quién llevarías a una comida familiar?'},
 {'tema': 'ELECCIONES', 'nivel': '💣 BOMBA', 'pregunta': '¿Con quién sobrevivirías mejor una semana sin móvil?'},
 {'tema': 'ELECCIONES', 'nivel': '🟡 SALSEO', 'pregunta': '¿A quién pedirías una opinión brutalmente sincera?'},
 {'tema': 'ELECCIONES', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién guardaría mejor una sorpresa?'},
 {'tema': 'ELECCIONES', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿A quién elegirías para investigar un cotilleo contigo?'},
 {'tema': 'ELECCIONES', 'nivel': '💣 BOMBA', 'pregunta': '¿Quién conseguiría hacerte reír en un día horrible?'},
 {'tema': 'ELECCIONES', 'nivel': '🟡 SALSEO', 'pregunta': '¿Quién te sacaría de un apuro sin hacer preguntas?'},
 {'tema': 'ELECCIONES', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Con quién compartirías habitación durante una quedada?'},
 {'tema': 'ELECCIONES',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Quién escribiría mejor un mensaje importante en tu nombre?'},
 {'tema': 'ELECCIONES', 'nivel': '💣 BOMBA', 'pregunta': '¿Por quién apostarías todo a que cumple su palabra?'},
 {'tema': 'ELECCIONES', 'nivel': '🟡 SALSEO', 'pregunta': '¿A quién llevarías a una boda donde no conoces a nadie?'},
 {'tema': 'ELECCIONES', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién descubriría mejor quién está mintiendo?'},
 {'tema': 'ELECCIONES',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿A quién contarías una barbaridad confiando en que no te juzgue?'},
 {'tema': 'ELECCIONES', 'nivel': '💣 BOMBA', 'pregunta': '¿Con quién preferirías quedarte atrapado/a en un aeropuerto?'},
 {'tema': 'ELECCIONES',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Si desapareciera el grupo mañana, ¿con quién seguirías hablando seguro?'},
 {'tema': 'ELECCIONES',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿A quién dejarías organizar una quedada sin supervisión?'},
 {'tema': 'ELECCIONES',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Quién sería tu mejor aliado/a en un problema dentro del grupo?'},
 {'tema': 'ELECCIONES',
  'nivel': '💣 BOMBA',
  'pregunta': 'Si tuvieras que compartir un premio con alguien, ¿a quién elegirías?'},
 {'tema': 'JUICIOS', 'nivel': '🟡 SALSEO', 'pregunta': '¿Quién es el más cotilla?'},
 {'tema': 'JUICIOS', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién es el más dramático/a?'},
 {'tema': 'JUICIOS', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién es el más imprevisible?'},
 {'tema': 'JUICIOS', 'nivel': '💣 BOMBA', 'pregunta': '¿Quién es el más competitivo/a?'},
 {'tema': 'JUICIOS', 'nivel': '🟡 SALSEO', 'pregunta': '¿Quién es el más cabezota?'},
 {'tema': 'JUICIOS', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién tiene más paciencia?'},
 {'tema': 'JUICIOS', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién tiene menos filtro?'},
 {'tema': 'JUICIOS', 'nivel': '💣 BOMBA', 'pregunta': '¿Quién observa más de lo que habla?'},
 {'tema': 'JUICIOS', 'nivel': '🟡 SALSEO', 'pregunta': '¿Quién es más fácil de picar?'},
 {'tema': 'JUICIOS', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién es más difícil de engañar?'},
 {'tema': 'JUICIOS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Quién podría convencer a cualquiera de casi cualquier cosa?'},
 {'tema': 'JUICIOS', 'nivel': '💣 BOMBA', 'pregunta': '¿Quién tiene más cara de no haber roto un plato y es mentira?'},
 {'tema': 'JUICIOS', 'nivel': '🟡 SALSEO', 'pregunta': '¿Quién se metería en un lío sin buscarlo?'},
 {'tema': 'JUICIOS', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién saldría mejor de un interrogatorio?'},
 {'tema': 'JUICIOS', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién sería peor mintiendo?'},
 {'tema': 'JUICIOS', 'nivel': '💣 BOMBA', 'pregunta': '¿Quién tiene más posibilidades de tener una doble vida?'},
 {'tema': 'JUICIOS', 'nivel': '🟡 SALSEO', 'pregunta': '¿Quién tiene más historias que todavía no ha contado?'},
 {'tema': 'JUICIOS', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién podría sorprender más en una quedada?'},
 {'tema': 'JUICIOS', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién habla más y cuenta menos realmente?'},
 {'tema': 'JUICIOS', 'nivel': '💣 BOMBA', 'pregunta': '¿Quién es más reservado/a aunque no lo parezca?'},
 {'tema': 'JUICIOS',
  'nivel': '🟡 SALSEO',
  'pregunta': '¿Quién tiene mejor memoria para recordar lo que dijeron los demás?'},
 {'tema': 'JUICIOS', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién podría ser detective?'},
 {'tema': 'JUICIOS', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién exageraría más una historia al contarla?'},
 {'tema': 'JUICIOS', 'nivel': '💣 BOMBA', 'pregunta': '¿Quién convertiría una tontería en un debate de dos horas?'},
 {'tema': 'JUICIOS', 'nivel': '🟡 SALSEO', 'pregunta': '¿Quién desaparecería una semana y volvería como si nada?'},
 {'tema': 'JUICIOS', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién podría hacerse amigo/a de cualquiera?'},
 {'tema': 'JUICIOS', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién tiene más facilidad para caer bien al principio?'},
 {'tema': 'JUICIOS', 'nivel': '💣 BOMBA', 'pregunta': '¿Quién mejora más cuanto más lo conoces?'},
 {'tema': 'JUICIOS', 'nivel': '🟡 SALSEO', 'pregunta': '¿Quién empeora cuando coge demasiada confianza? 😂'},
 {'tema': 'JUICIOS', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién sería más difícil de soportar en vacaciones largas?'},
 {'tema': 'JUICIOS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Quién se enteraría de un secreto sin que nadie se lo contara?'},
 {'tema': 'JUICIOS', 'nivel': '💣 BOMBA', 'pregunta': '¿Quién podría hacerse viral por una tontería?'},
 {'tema': 'JUICIOS', 'nivel': '🟡 SALSEO', 'pregunta': '¿Quién ganaría un reality de convivencia?'},
 {'tema': 'JUICIOS', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién sería expulsado/a primero de un reality?'},
 {'tema': 'JUICIOS', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién manipularía mejor una votación sin que se notara?'},
 {'tema': 'JUICIOS', 'nivel': '💣 BOMBA', 'pregunta': '¿Quién sería peor enemigo/a?'},
 {'tema': 'JUICIOS', 'nivel': '🟡 SALSEO', 'pregunta': '¿Quién sería más leal como amigo/a?'},
 {'tema': 'JUICIOS', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién podría sorprender a todos con una decisión radical?'},
 {'tema': 'JUICIOS', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién es más difícil de descifrar?'},
 {'tema': 'JUICIOS', 'nivel': '💣 BOMBA', 'pregunta': '¿Quién conoce mejor las debilidades de los demás?'},
 {'tema': 'HIPOTETICOS',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Si hubiera un detector de mentiras, ¿a quién sentarías primero?'},
 {'tema': 'HIPOTETICOS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si se filtraran todos los privados, ¿quién tendría más problemas?'},
 {'tema': 'HIPOTETICOS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si vivierais juntos un mes, ¿quién provocaría el primer conflicto?'},
 {'tema': 'HIPOTETICOS',
  'nivel': '💣 BOMBA',
  'pregunta': 'Si hicierais un reality, ¿qué dos personas darían más contenido juntas?'},
 {'tema': 'HIPOTETICOS',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Si el grupo fuera una familia, ¿quién sería el hijo problemático?'},
 {'tema': 'HIPOTETICOS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si hubiera una emergencia en una quedada, ¿quién tomaría el control?'},
 {'tema': 'HIPOTETICOS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si estuvierais perdidos en una ciudad, ¿quién empeoraría la situación?'},
 {'tema': 'HIPOTETICOS',
  'nivel': '💣 BOMBA',
  'pregunta': 'Si hubiera que esconder algo importante, ¿quién metería la pata primero?'},
 {'tema': 'HIPOTETICOS',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Si pudieras obligar a dos miembros a resolver una conversación pendiente, ¿a quiénes?'},
 {'tema': 'HIPOTETICOS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si hubiera un juicio ficticio, ¿quién tendría más cargos acumulados? 😂'},
 {'tema': 'HIPOTETICOS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si hubiera que infiltrarse en otro grupo, ¿quién lo haría mejor?'},
 {'tema': 'HIPOTETICOS',
  'nivel': '💣 BOMBA',
  'pregunta': 'Si todos enseñaran su historial de búsquedas, ¿quién daría más juego?'},
 {'tema': 'HIPOTETICOS',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Si emparejaras a dos como compañeros de piso, ¿qué combinación sería un desastre?'},
 {'tema': 'HIPOTETICOS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si dos organizaran una fiesta, ¿quiénes garantizarían el caos?'},
 {'tema': 'HIPOTETICOS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si hubiera un confesionario anónimo, ¿quién lo usaría más?'},
 {'tema': 'HIPOTETICOS',
  'nivel': '💣 BOMBA',
  'pregunta': 'Si alguien tuviera que contar toda la verdad una hora, ¿a quién elegirías?'},
 {'tema': 'HIPOTETICOS',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Si todos se calificaran anónimamente, ¿quién se llevaría la mayor sorpresa?'},
 {'tema': 'HIPOTETICOS', 'nivel': '🔴 SIN FILTRO', 'pregunta': 'Si el grupo tuviera un villano oficial, ¿quién sería?'},
 {'tema': 'HIPOTETICOS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si crearas una alianza secreta con dos miembros, ¿a quiénes escogerías?'},
 {'tema': 'HIPOTETICOS',
  'nivel': '💣 BOMBA',
  'pregunta': 'Si pudieras saber quién menciona más tu nombre por privado, ¿querrías saberlo?'},
 {'tema': 'HIPOTETICOS',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Si alguien pudiera leer la mente durante una partida, ¿a quién vigilarías?'},
 {'tema': 'HIPOTETICOS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si solo una persona pudiera conservar todos los secretos del grupo, ¿quién debería ser?'},
 {'tema': 'HIPOTETICOS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si hubiera que votar a la persona menos fiable, ¿quién sufriría más?'},
 {'tema': 'HIPOTETICOS',
  'nivel': '💣 BOMBA',
  'pregunta': 'Si todos tuvieran una etiqueta de advertencia, ¿cuál pondrías a alguien y a quién?'},
 {'tema': 'HIPOTETICOS',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Si pudieras cambiar una costumbre de alguien, ¿de quién y cuál?'},
 {'tema': 'HIPOTETICOS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si pudieras hacer una pregunta anónima obligatoria a alguien, ¿qué preguntarías y a quién?'},
 {'tema': 'HIPOTETICOS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si supieras que alguien ha mentido hoy, ¿de quién sospecharías?'},
 {'tema': 'HIPOTETICOS',
  'nivel': '💣 BOMBA',
  'pregunta': 'Si alguien tuviera que leer sus diez últimos privados, ¿a quién elegirías?'},
 {'tema': 'HIPOTETICOS',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Si pudieras escuchar una conversación ocurrida sin ti, ¿cuál te interesaría?'},
 {'tema': 'HIPOTETICOS', 'nivel': '🔴 SIN FILTRO', 'pregunta': 'Si hubiera un apocalipsis, ¿a quién dejarías al mando?'},
 {'tema': 'HIPOTETICOS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si alguien tuviera inmunidad para decir lo que quiera cinco minutos, ¿a quién se la darías?'},
 {'tema': 'HIPOTETICOS',
  'nivel': '💣 BOMBA',
  'pregunta': 'Si pudieras borrar una discusión del grupo, ¿cuál borrarías?'},
 {'tema': 'HIPOTETICOS',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Si mañana hubiera una quedada sorpresa, ¿quién crees que no aparecería ni de broma?'},
 {'tema': 'HIPOTETICOS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si hubiera un premio a la persona más polémica, ¿quién ganaría?'},
 {'tema': 'HIPOTETICOS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si hubiera que elegir portavoz, ¿quién representaría mejor al grupo?'},
 {'tema': 'HIPOTETICOS',
  'nivel': '💣 BOMBA',
  'pregunta': 'Si Telegram cerrara mañana, ¿quién mantendría unido al grupo?'},
 {'tema': 'HIPOTETICOS',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Si pudieras ver una estadística secreta del grupo, ¿qué dato querrías conocer?'},
 {'tema': 'HIPOTETICOS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si pudieras saber quién te ha nombrado más veces cuando no estabas, ¿lo mirarías?'},
 {'tema': 'HIPOTETICOS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si tuvieras que juntar a dos personas para resolver un misterio, ¿quiénes?'},
 {'tema': 'HIPOTETICOS',
  'nivel': '💣 BOMBA',
  'pregunta': 'Si el grupo tuviera que elegir a su persona más caótica, ¿quién ganaría?'},
 {'tema': 'CONFESIONES_GRUPO',
  'nivel': '🟡 SALSEO',
  'pregunta': '¿Has hablado mal por privado de alguien que está ahora mismo aquí?'},
 {'tema': 'CONFESIONES_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Has evitado responder a alguien del grupo a propósito?'},
 {'tema': 'CONFESIONES_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Has cambiado una respuesta de DadoNet para no señalar a quien realmente pensabas?'},
 {'tema': 'CONFESIONES_GRUPO', 'nivel': '💣 BOMBA', 'pregunta': '¿Has mentido alguna vez jugando a DadoNet?'},
 {'tema': 'CONFESIONES_GRUPO',
  'nivel': '🟡 SALSEO',
  'pregunta': '¿Has votado en una encuesta solo para picar a alguien?'},
 {'tema': 'CONFESIONES_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Has hecho una captura del grupo para comentarla fuera?'},
 {'tema': 'CONFESIONES_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Has hablado de un miembro con otro sin que esa persona lo supiera?'},
 {'tema': 'CONFESIONES_GRUPO',
  'nivel': '💣 BOMBA',
  'pregunta': '¿Has fingido no haber leído un drama cuando te lo sabías entero?'},
 {'tema': 'CONFESIONES_GRUPO',
  'nivel': '🟡 SALSEO',
  'pregunta': '¿Has entrado al grupo alguna vez solo porque viste que había salseo?'},
 {'tema': 'CONFESIONES_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Has dejado de escribir porque estaba hablando alguien con quien no querías interactuar?'},
 {'tema': 'CONFESIONES_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Has borrado un mensaje porque temías que alguien concreto lo interpretara mal?'},
 {'tema': 'CONFESIONES_GRUPO',
  'nivel': '💣 BOMBA',
  'pregunta': '¿Has escrito algo pensando específicamente en provocar la reacción de alguien?'},
 {'tema': 'CONFESIONES_GRUPO',
  'nivel': '🟡 SALSEO',
  'pregunta': '¿Has esperado a que apareciera una persona concreta para participar más?'},
 {'tema': 'CONFESIONES_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Has ignorado deliberadamente el mensaje de alguien?'},
 {'tema': 'CONFESIONES_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Has pensado alguna vez que alguien debería abandonar el grupo?'},
 {'tema': 'CONFESIONES_GRUPO',
  'nivel': '💣 BOMBA',
  'pregunta': '¿Has defendido a alguien aunque en privado pensabas que no tenía razón?'},
 {'tema': 'CONFESIONES_GRUPO',
  'nivel': '🟡 SALSEO',
  'pregunta': '¿Has dado la razón a alguien solo para terminar una discusión?'},
 {'tema': 'CONFESIONES_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Has contado fuera cosas que pasan dentro del grupo?'},
 {'tema': 'CONFESIONES_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Has preguntado por privado qué pasó después de perderte un drama?'},
 {'tema': 'CONFESIONES_GRUPO',
  'nivel': '💣 BOMBA',
  'pregunta': '¿Tienes un privado sobre alguien de aquí que te daría apuro que leyera?'},
 {'tema': 'CONFESIONES_GRUPO',
  'nivel': '🟡 SALSEO',
  'pregunta': "¿Has pensado 'esta persona me cae peor cada día' sobre alguien de aquí?"},
 {'tema': 'CONFESIONES_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Has cambiado de opinión sobre alguien por algo que contó jugando?'},
 {'tema': 'CONFESIONES_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Has respondido pensando más en cómo quedabas tú que en decir la verdad?'},
 {'tema': 'CONFESIONES_GRUPO',
  'nivel': '💣 BOMBA',
  'pregunta': '¿Has evitado nombrar a alguien porque sabías que podía enfadarse?'},
 {'tema': 'CONFESIONES_GRUPO',
  'nivel': '🟡 SALSEO',
  'pregunta': '¿Has pensado que una respuesta iba claramente por ti aunque no te nombraran?'},
 {'tema': 'CONFESIONES_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Has sentido celos de la amistad entre dos personas del grupo?'},
 {'tema': 'CONFESIONES_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Has sentido que alguien te excluía de una conversación?'},
 {'tema': 'CONFESIONES_GRUPO',
  'nivel': '💣 BOMBA',
  'pregunta': '¿Has sospechado que existe un grupo paralelo donde se habla de aquí?'},
 {'tema': 'CONFESIONES_GRUPO',
  'nivel': '🟡 SALSEO',
  'pregunta': '¿Has pensado que alguien interpreta un personaje dentro del grupo?'},
 {'tema': 'CONFESIONES_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Has usado una broma para decir algo que realmente pensabas?'},
 {'tema': 'CONFESIONES_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Has dejado una pregunta sin responder porque la verdad era demasiado comprometida?'},
 {'tema': 'CONFESIONES_GRUPO', 'nivel': '💣 BOMBA', 'pregunta': '¿Has releído mensajes antiguos para comprobar algo?'},
 {'tema': 'CONFESIONES_GRUPO',
  'nivel': '🟡 SALSEO',
  'pregunta': '¿Has buscado las redes de un miembro por pura curiosidad?'},
 {'tema': 'CONFESIONES_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Has preguntado a otra persona qué opinión tiene sobre alguien de aquí?'},
 {'tema': 'CONFESIONES_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Has notado tensión entre dos miembros antes de que ellos reconocieran nada?'},
 {'tema': 'CONFESIONES_GRUPO', 'nivel': '💣 BOMBA', 'pregunta': '¿Has pensado que alguien te estaba evitando?'},
 {'tema': 'CONFESIONES_GRUPO',
  'nivel': '🟡 SALSEO',
  'pregunta': '¿Has fingido que una respuesta no te molestó cuando sí lo hizo?'},
 {'tema': 'CONFESIONES_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Te preocupa saber qué se dice de ti cuando no estás?'},
 {'tema': 'CONFESIONES_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Tienes una opinión sobre alguien que abriría un melón enorme si la dijeras?'},
 {'tema': 'CONFESIONES_GRUPO',
  'nivel': '💣 BOMBA',
  'pregunta': '¿Has cambiado tu forma de tratar a alguien por algo que te contaron de esa persona?'},
 {'tema': 'PERSONALES_POTENTES',
  'nivel': '🟡 SALSEO',
  'pregunta': '¿Cuál es la mentira más absurda que has contado para quitarte a alguien de encima?'},
 {'tema': 'PERSONALES_POTENTES',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Cuál ha sido tu peor experiencia conociendo a alguien por internet?'},
 {'tema': 'PERSONALES_POTENTES',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Qué es lo más vergonzoso que te ha ocurrido durante el sexo?'},
 {'tema': 'PERSONALES_POTENTES',
  'nivel': '💣 BOMBA',
  'pregunta': '¿Has descubierto que alguien hablaba mal de ti y fingiste no saberlo?'},
 {'tema': 'PERSONALES_POTENTES',
  'nivel': '🟡 SALSEO',
  'pregunta': '¿Has mantenido conversación con alguien que no te interesaba porque te gustaba la atención?'},
 {'tema': 'PERSONALES_POTENTES',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Qué es lo más rastrero que has hecho por celos?'},
 {'tema': 'PERSONALES_POTENTES',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Has cotilleado tanto a alguien en redes que descubriste algo que habría sido mejor no saber?'},
 {'tema': 'PERSONALES_POTENTES',
  'nivel': '💣 BOMBA',
  'pregunta': '¿Has enseñado una conversación privada que habías prometido no enseñar?'},
 {'tema': 'PERSONALES_POTENTES',
  'nivel': '🟡 SALSEO',
  'pregunta': '¿Has fingido que alguien te caía bien porque te convenía?'},
 {'tema': 'PERSONALES_POTENTES',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Has contado un secreto que prometiste guardar?'},
 {'tema': 'PERSONALES_POTENTES',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Has negado haber dicho algo sabiendo que sí lo dijiste?'},
 {'tema': 'PERSONALES_POTENTES',
  'nivel': '💣 BOMBA',
  'pregunta': '¿Has bloqueado a alguien esperando que buscara otra forma de contactarte?'},
 {'tema': 'PERSONALES_POTENTES',
  'nivel': '🟡 SALSEO',
  'pregunta': '¿Has leído una conversación que sabías que no debías leer?'},
 {'tema': 'PERSONALES_POTENTES',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Has utilizado información privada de alguien durante una discusión?'},
 {'tema': 'PERSONALES_POTENTES',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Has seguido hablando con alguien solo para enterarte de un cotilleo?'},
 {'tema': 'PERSONALES_POTENTES',
  'nivel': '💣 BOMBA',
  'pregunta': '¿Has fingido no ver un mensaje para hacerte de rogar?'},
 {'tema': 'PERSONALES_POTENTES',
  'nivel': '🟡 SALSEO',
  'pregunta': '¿Has mentido sobre dónde estabas para evitar a alguien?'},
 {'tema': 'PERSONALES_POTENTES',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Has descubierto una infidelidad ajena y decidido no decir nada?'},
 {'tema': 'PERSONALES_POTENTES',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Has sido cómplice de una mentira sentimental de un amigo/a?'},
 {'tema': 'PERSONALES_POTENTES',
  'nivel': '💣 BOMBA',
  'pregunta': '¿Has hablado mal de alguien y después actuado con normalidad delante de esa persona?'},
 {'tema': 'PERSONALES_POTENTES',
  'nivel': '🟡 SALSEO',
  'pregunta': '¿Has intentado provocar celos a alguien a propósito?'},
 {'tema': 'PERSONALES_POTENTES',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': "¿Has revisado seguidores y 'me gusta' de alguien para sacar conclusiones?"},
 {'tema': 'PERSONALES_POTENTES',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Has descubierto algo importante sobre alguien investigando sus redes?'},
 {'tema': 'PERSONALES_POTENTES',
  'nivel': '💣 BOMBA',
  'pregunta': '¿Has mentido diciendo que algo no te importaba cuando estabas rabioso/a?'},
 {'tema': 'PERSONALES_POTENTES', 'nivel': '🟡 SALSEO', 'pregunta': '¿Has usado una cuenta secundaria para cotillear?'},
 {'tema': 'PERSONALES_POTENTES',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Has borrado mensajes para que otra persona no pudiera verlos?'},
 {'tema': 'PERSONALES_POTENTES',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Has contado una discusión haciendo que tú quedaras bastante mejor de lo que realmente quedaste?'},
 {'tema': 'PERSONALES_POTENTES',
  'nivel': '💣 BOMBA',
  'pregunta': '¿Has fingido no conocer un cotilleo que ya sabías entero?'},
 {'tema': 'PERSONALES_POTENTES',
  'nivel': '🟡 SALSEO',
  'pregunta': '¿Has vuelto a hablar con alguien solo porque estabas aburrido/a?'},
 {'tema': 'PERSONALES_POTENTES',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Has ignorado deliberadamente a alguien para castigarlo?'},
 {'tema': 'PERSONALES_POTENTES',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Has hecho algo por despecho que jamás admitirías delante de la persona afectada?'},
 {'tema': 'PERSONALES_POTENTES',
  'nivel': '💣 BOMBA',
  'pregunta': '¿Has dejado que dos personas discutieran por algo que tú podías aclarar?'},
 {'tema': 'PERSONALES_POTENTES',
  'nivel': '🟡 SALSEO',
  'pregunta': "¿Has dicho 'no pasa nada' cuando claramente sí pasaba?"},
 {'tema': 'PERSONALES_POTENTES',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Has preguntado por alguien fingiendo casualidad cuando realmente querías información?'},
 {'tema': 'PERSONALES_POTENTES',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Has juzgado a alguien por hacer algo que tú también has hecho?'},
 {'tema': 'PERSONALES_POTENTES', 'nivel': '💣 BOMBA', 'pregunta': '¿Cuál es la mayor hipocresía que reconoces en ti?'},
 {'tema': 'PERSONALES_POTENTES',
  'nivel': '🟡 SALSEO',
  'pregunta': '¿Has fingido estar ocupado/a para evitar a alguien que no querías ver?'},
 {'tema': 'PERSONALES_POTENTES',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Has mantenido una amistad por compromiso cuando ya no soportabas a esa persona?'},
 {'tema': 'PERSONALES_POTENTES',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Has hecho algo únicamente para conseguir una reacción de otra persona?'},
 {'tema': 'PERSONALES_POTENTES',
  'nivel': '💣 BOMBA',
  'pregunta': '¿Qué cosa sobre ti te daría más apuro que alguien descubriera cotilleando tu móvil?'},
 {'tema': 'DIRECTAS', 'nivel': '🟡 SALSEO', 'pregunta': 'Elige a alguien y dile una cualidad y un defecto reales.'},
 {'tema': 'DIRECTAS', 'nivel': '🔴 SIN FILTRO', 'pregunta': 'Elige a alguien y dile qué primera impresión te dio.'},
 {'tema': 'DIRECTAS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Elige a alguien y dile en qué crees que se equivoca sobre sí mismo/a.'},
 {'tema': 'DIRECTAS', 'nivel': '💣 BOMBA', 'pregunta': 'Elige a alguien y dile qué crees que debería mejorar.'},
 {'tema': 'DIRECTAS',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Elige a alguien y dile algo que te cae bien y algo que te irrita.'},
 {'tema': 'DIRECTAS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Elige a alguien con quien hables poco y explica por qué no habéis conectado más.'},
 {'tema': 'DIRECTAS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Elige a alguien que te genere curiosidad y explica exactamente por qué.'},
 {'tema': 'DIRECTAS', 'nivel': '💣 BOMBA', 'pregunta': 'Elige a alguien que te intimide un poco y explica por qué.'},
 {'tema': 'DIRECTAS',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Elige a alguien cuya opinión valores más de lo que probablemente sabe.'},
 {'tema': 'DIRECTAS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Elige a alguien de quien te gustaría recibir una disculpa.'},
 {'tema': 'DIRECTAS', 'nivel': '🔴 SIN FILTRO', 'pregunta': 'Elige a alguien a quien tú deberías pedirle disculpas.'},
 {'tema': 'DIRECTAS', 'nivel': '💣 BOMBA', 'pregunta': 'Elige a alguien y di qué crees que piensa de ti.'},
 {'tema': 'DIRECTAS',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Elige a alguien y di qué crees que peor lleva de tu personalidad.'},
 {'tema': 'DIRECTAS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Elige a alguien y di en qué os parecéis aunque no sea evidente.'},
 {'tema': 'DIRECTAS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Elige a alguien y di qué podría hacer para caerte mucho peor.'},
 {'tema': 'DIRECTAS',
  'nivel': '💣 BOMBA',
  'pregunta': 'Elige a alguien y di qué tendría que pasar para que confiaras completamente en él/ella.'},
 {'tema': 'DIRECTAS', 'nivel': '🟡 SALSEO', 'pregunta': 'Elige a alguien y cuenta qué cosa suya te ha sorprendido más.'},
 {'tema': 'DIRECTAS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Elige a alguien y di qué pregunta nunca te atreverías a hacerle.'},
 {'tema': 'DIRECTAS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Elige a alguien y di qué rumor sobre esa persona te creerías más fácilmente.'},
 {'tema': 'DIRECTAS', 'nivel': '💣 BOMBA', 'pregunta': 'Elige a alguien y di qué crees que sería incapaz de perdonar.'},
 {'tema': 'DIRECTAS',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Elige a alguien y di qué oculta mejor: enfado, tristeza, celos o inseguridad.'},
 {'tema': 'DIRECTAS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Elige a alguien y di qué crees que hace cuando se enfada de verdad.'},
 {'tema': 'DIRECTAS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Elige a alguien y di si confiarías en su versión de una pelea sin escuchar la otra.'},
 {'tema': 'DIRECTAS',
  'nivel': '💣 BOMBA',
  'pregunta': 'Elige a alguien y di qué papel desempeña realmente dentro del grupo.'},
 {'tema': 'DIRECTAS', 'nivel': '🟡 SALSEO', 'pregunta': 'Elige a alguien y dile algo que nunca le habías dicho.'},
 {'tema': 'DIRECTAS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Elige a alguien y di qué malinterpreta la gente sobre él/ella.'},
 {'tema': 'DIRECTAS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Elige a alguien y di qué tipo de secreto sí le confiarías.'},
 {'tema': 'DIRECTAS',
  'nivel': '💣 BOMBA',
  'pregunta': 'Elige a alguien y di qué crees que pensó de ti la primera vez que hablasteis.'},
 {'tema': 'DIRECTAS',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Elige a alguien y di si crees que te defendería estando tú ausente.'},
 {'tema': 'DIRECTAS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Elige a alguien y di si crees que alguna vez te ha puesto verde por privado.'},
 {'tema': 'DIRECTAS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Elige a alguien y di qué conversación pendiente podríais tener.'},
 {'tema': 'DIRECTAS',
  'nivel': '💣 BOMBA',
  'pregunta': 'Elige a alguien y di qué le preguntarías si supieras que no se va a ofender.'},
 {'tema': 'DIRECTAS',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Elige a alguien y di qué respuesta suya de DadoNet recuerdas más.'},
 {'tema': 'DIRECTAS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Elige a alguien y di qué cosa crees que jamás reconocería públicamente.'},
 {'tema': 'DIRECTAS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Elige a alguien y di en qué situación sería insoportable convivir con él/ella.'},
 {'tema': 'DIRECTAS',
  'nivel': '💣 BOMBA',
  'pregunta': 'Elige a alguien y di qué haría si supiera que hablan mal de él/ella.'},
 {'tema': 'DIRECTAS',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Elige a alguien y di qué consejo debería escuchar aunque no le guste.'},
 {'tema': 'DIRECTAS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Elige a alguien y di si sabe realmente la imagen que proyecta.'},
 {'tema': 'DIRECTAS',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Elige a alguien y di qué podría hacer para sorprenderte muchísimo.'},
 {'tema': 'DIRECTAS',
  'nivel': '💣 BOMBA',
  'pregunta': 'Elige a alguien y hazle ahora mismo una pregunta que normalmente no le harías.'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Señala a alguien del grupo: ¿quién crees que te sorprendería más con una confesión? (pensando solo en '
              'lo que has visto esta semana)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Señala a alguien del grupo: ¿quién crees que sabe más de ti de lo que imaginas? (por su forma de '
              'hablar)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Señala a alguien del grupo: ¿quién crees que te juzgaría menos si contaras algo fuerte? (por cómo '
              'reacciona en los juegos)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '💣 BOMBA',
  'pregunta': 'Señala a alguien del grupo: ¿quién crees que tendría una respuesta inesperada si le preguntaras por ti? '
              '(por lo que suele callarse)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Señala a alguien del grupo: ¿quién crees que te sorprendería más con una confesión? (sin poder elegir a '
              'tu persona habitual)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Señala a alguien del grupo: ¿quién crees que sabe más de ti de lo que imaginas? (pensando solo en lo '
              'que has visto esta semana)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Señala a alguien del grupo: ¿quién crees que te juzgaría menos si contaras algo fuerte? (por su forma '
              'de hablar)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '💣 BOMBA',
  'pregunta': 'Señala a alguien del grupo: ¿quién crees que tendría una respuesta inesperada si le preguntaras por ti? '
              '(por cómo reacciona en los juegos)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Señala a alguien del grupo: ¿quién crees que te sorprendería más con una confesión? (por lo que suele '
              'callarse)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Señala a alguien del grupo: ¿quién crees que sabe más de ti de lo que imaginas? (sin poder elegir a tu '
              'persona habitual)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Señala a alguien del grupo: ¿quién crees que te juzgaría menos si contaras algo fuerte? (pensando solo '
              'en lo que has visto esta semana)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '💣 BOMBA',
  'pregunta': 'Señala a alguien del grupo: ¿quién crees que tendría una respuesta inesperada si le preguntaras por ti? '
              '(por su forma de hablar)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Señala a alguien del grupo: ¿quién crees que te sorprendería más con una confesión? (por cómo reacciona '
              'en los juegos)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Señala a alguien del grupo: ¿quién crees que sabe más de ti de lo que imaginas? (por lo que suele '
              'callarse)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Señala a alguien del grupo: ¿quién crees que te juzgaría menos si contaras algo fuerte? (sin poder '
              'elegir a tu persona habitual)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '💣 BOMBA',
  'pregunta': 'Señala a alguien del grupo: ¿quién crees que tendría una respuesta inesperada si le preguntaras por ti? '
              '(pensando solo en lo que has visto esta semana)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Señala a alguien del grupo: ¿quién crees que te sorprendería más con una confesión? (por su forma de '
              'hablar)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Señala a alguien del grupo: ¿quién crees que sabe más de ti de lo que imaginas? (por cómo reacciona en '
              'los juegos)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Señala a alguien del grupo: ¿quién crees que te juzgaría menos si contaras algo fuerte? (por lo que '
              'suele callarse)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '💣 BOMBA',
  'pregunta': 'Señala a alguien del grupo: ¿quién crees que tendría una respuesta inesperada si le preguntaras por ti? '
              '(sin poder elegir a tu persona habitual)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Señala a alguien del grupo: ¿quién crees que te sorprendería más con una confesión? (pensando solo en '
              'lo que has visto esta semana)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Señala a alguien del grupo: ¿quién crees que sabe más de ti de lo que imaginas? (por su forma de '
              'hablar)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Señala a alguien del grupo: ¿quién crees que te juzgaría menos si contaras algo fuerte? (por cómo '
              'reacciona en los juegos)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '💣 BOMBA',
  'pregunta': 'Señala a alguien del grupo: ¿quién crees que tendría una respuesta inesperada si le preguntaras por ti? '
              '(por lo que suele callarse)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Señala a alguien del grupo: ¿quién crees que te sorprendería más con una confesión? (sin poder elegir a '
              'tu persona habitual)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Señala a alguien del grupo: ¿quién crees que sabe más de ti de lo que imaginas? (pensando solo en lo '
              'que has visto esta semana)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Señala a alguien del grupo: ¿quién crees que te juzgaría menos si contaras algo fuerte? (por su forma '
              'de hablar)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '💣 BOMBA',
  'pregunta': 'Señala a alguien del grupo: ¿quién crees que tendría una respuesta inesperada si le preguntaras por ti? '
              '(por cómo reacciona en los juegos)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Señala a alguien del grupo: ¿quién crees que te sorprendería más con una confesión? (por lo que suele '
              'callarse)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Señala a alguien del grupo: ¿quién crees que sabe más de ti de lo que imaginas? (sin poder elegir a tu '
              'persona habitual)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Señala a alguien del grupo: ¿quién crees que te juzgaría menos si contaras algo fuerte? (pensando solo '
              'en lo que has visto esta semana)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '💣 BOMBA',
  'pregunta': 'Señala a alguien del grupo: ¿quién crees que tendría una respuesta inesperada si le preguntaras por ti? '
              '(por su forma de hablar)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Señala a alguien del grupo: ¿quién crees que te sorprendería más con una confesión? (por cómo reacciona '
              'en los juegos)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Señala a alguien del grupo: ¿quién crees que sabe más de ti de lo que imaginas? (por lo que suele '
              'callarse)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Señala a alguien del grupo: ¿quién crees que te juzgaría menos si contaras algo fuerte? (sin poder '
              'elegir a tu persona habitual)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '💣 BOMBA',
  'pregunta': 'Señala a alguien del grupo: ¿quién crees que tendría una respuesta inesperada si le preguntaras por ti? '
              '(pensando solo en lo que has visto esta semana)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Señala a alguien del grupo: ¿quién crees que te sorprendería más con una confesión? (por su forma de '
              'hablar)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Señala a alguien del grupo: ¿quién crees que sabe más de ti de lo que imaginas? (por cómo reacciona en '
              'los juegos)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Señala a alguien del grupo: ¿quién crees que te juzgaría menos si contaras algo fuerte? (por lo que '
              'suele callarse)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '💣 BOMBA',
  'pregunta': 'Señala a alguien del grupo: ¿quién crees que tendría una respuesta inesperada si le preguntaras por ti? '
              '(sin poder elegir a tu persona habitual)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Si tuvieras que elegir ahora: ¿quién del grupo te inspira más confianza? (pensando solo en lo que has '
              'visto esta semana)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si tuvieras que elegir ahora: ¿quién del grupo te genera más curiosidad? (por su forma de hablar)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si tuvieras que elegir ahora: ¿quién del grupo crees que oculta más cosas? (por cómo reacciona en los '
              'juegos)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '💣 BOMBA',
  'pregunta': 'Si tuvieras que elegir ahora: ¿quién del grupo te resultaría más difícil de descifrar? (por lo que '
              'suele callarse)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Si tuvieras que elegir ahora: ¿quién del grupo te inspira más confianza? (sin poder elegir a tu persona '
              'habitual)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si tuvieras que elegir ahora: ¿quién del grupo te genera más curiosidad? (pensando solo en lo que has '
              'visto esta semana)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si tuvieras que elegir ahora: ¿quién del grupo crees que oculta más cosas? (por su forma de hablar)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '💣 BOMBA',
  'pregunta': 'Si tuvieras que elegir ahora: ¿quién del grupo te resultaría más difícil de descifrar? (por cómo '
              'reacciona en los juegos)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Si tuvieras que elegir ahora: ¿quién del grupo te inspira más confianza? (por lo que suele callarse)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si tuvieras que elegir ahora: ¿quién del grupo te genera más curiosidad? (sin poder elegir a tu persona '
              'habitual)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si tuvieras que elegir ahora: ¿quién del grupo crees que oculta más cosas? (pensando solo en lo que has '
              'visto esta semana)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '💣 BOMBA',
  'pregunta': 'Si tuvieras que elegir ahora: ¿quién del grupo te resultaría más difícil de descifrar? (por su forma de '
              'hablar)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Si tuvieras que elegir ahora: ¿quién del grupo te inspira más confianza? (por cómo reacciona en los '
              'juegos)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si tuvieras que elegir ahora: ¿quién del grupo te genera más curiosidad? (por lo que suele callarse)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si tuvieras que elegir ahora: ¿quién del grupo crees que oculta más cosas? (sin poder elegir a tu '
              'persona habitual)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '💣 BOMBA',
  'pregunta': 'Si tuvieras que elegir ahora: ¿quién del grupo te resultaría más difícil de descifrar? (pensando solo '
              'en lo que has visto esta semana)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Si tuvieras que elegir ahora: ¿quién del grupo te inspira más confianza? (por su forma de hablar)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si tuvieras que elegir ahora: ¿quién del grupo te genera más curiosidad? (por cómo reacciona en los '
              'juegos)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si tuvieras que elegir ahora: ¿quién del grupo crees que oculta más cosas? (por lo que suele callarse)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '💣 BOMBA',
  'pregunta': 'Si tuvieras que elegir ahora: ¿quién del grupo te resultaría más difícil de descifrar? (sin poder '
              'elegir a tu persona habitual)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Si tuvieras que elegir ahora: ¿quién del grupo te inspira más confianza? (pensando solo en lo que has '
              'visto esta semana)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si tuvieras que elegir ahora: ¿quién del grupo te genera más curiosidad? (por su forma de hablar)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si tuvieras que elegir ahora: ¿quién del grupo crees que oculta más cosas? (por cómo reacciona en los '
              'juegos)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '💣 BOMBA',
  'pregunta': 'Si tuvieras que elegir ahora: ¿quién del grupo te resultaría más difícil de descifrar? (por lo que '
              'suele callarse)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Si tuvieras que elegir ahora: ¿quién del grupo te inspira más confianza? (sin poder elegir a tu persona '
              'habitual)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si tuvieras que elegir ahora: ¿quién del grupo te genera más curiosidad? (pensando solo en lo que has '
              'visto esta semana)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si tuvieras que elegir ahora: ¿quién del grupo crees que oculta más cosas? (por su forma de hablar)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '💣 BOMBA',
  'pregunta': 'Si tuvieras que elegir ahora: ¿quién del grupo te resultaría más difícil de descifrar? (por cómo '
              'reacciona en los juegos)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Si tuvieras que elegir ahora: ¿quién del grupo te inspira más confianza? (por lo que suele callarse)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si tuvieras que elegir ahora: ¿quién del grupo te genera más curiosidad? (sin poder elegir a tu persona '
              'habitual)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si tuvieras que elegir ahora: ¿quién del grupo crees que oculta más cosas? (pensando solo en lo que has '
              'visto esta semana)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '💣 BOMBA',
  'pregunta': 'Si tuvieras que elegir ahora: ¿quién del grupo te resultaría más difícil de descifrar? (por su forma de '
              'hablar)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Si tuvieras que elegir ahora: ¿quién del grupo te inspira más confianza? (por cómo reacciona en los '
              'juegos)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si tuvieras que elegir ahora: ¿quién del grupo te genera más curiosidad? (por lo que suele callarse)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si tuvieras que elegir ahora: ¿quién del grupo crees que oculta más cosas? (sin poder elegir a tu '
              'persona habitual)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '💣 BOMBA',
  'pregunta': 'Si tuvieras que elegir ahora: ¿quién del grupo te resultaría más difícil de descifrar? (pensando solo '
              'en lo que has visto esta semana)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🟡 SALSEO',
  'pregunta': 'Si tuvieras que elegir ahora: ¿quién del grupo te inspira más confianza? (por su forma de hablar)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si tuvieras que elegir ahora: ¿quién del grupo te genera más curiosidad? (por cómo reacciona en los '
              'juegos)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': 'Si tuvieras que elegir ahora: ¿quién del grupo crees que oculta más cosas? (por lo que suele callarse)'},
 {'tema': 'DINAMICA_GRUPO',
  'nivel': '💣 BOMBA',
  'pregunta': 'Si tuvieras que elegir ahora: ¿quién del grupo te resultaría más difícil de descifrar? (sin poder '
              'elegir a tu persona habitual)'},
 {'tema': 'ATRACCION', 'nivel': '🟡 SALSEO', 'pregunta': '¿Quién del grupo te atrae más físicamente?'},
 {'tema': 'ATRACCION', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Con quién tendrías más química en persona?'},
 {'tema': 'ATRACCION', 'nivel': '💣 BOMBA', 'pregunta': '¿A quién besarías si tuvieras que elegir ahora?'},
 {'tema': 'ATRACCION', 'nivel': '🟡 SALSEO', 'pregunta': '¿Con quién tendrías una cita por pura curiosidad?'},
 {'tema': 'ATRACCION', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién crees que liga mejor?'},
 {'tema': 'ATRACCION', 'nivel': '💣 BOMBA', 'pregunta': '¿Quién crees que recibe más proposiciones por privado?'},
 {'tema': 'ATRACCION',
  'nivel': '🟡 SALSEO',
  'pregunta': '¿Quién podría conquistarte por conversación aunque inicialmente no te atrajera?'},
 {'tema': 'ATRACCION',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Con quién crees que sería más peligroso confundir amistad y atracción?'},
 {'tema': 'ATRACCION', 'nivel': '💣 BOMBA', 'pregunta': '¿Quién crees que tiene más sex appeal sin intentarlo?'},
 {'tema': 'ATRACCION',
  'nivel': '🟡 SALSEO',
  'pregunta': '¿A quién te daría más curiosidad conocer estando ambos solteros?'},
 {'tema': 'ATRACCION', 'nivel': '🔴 SIN FILTRO', 'pregunta': "¿Quién podría hacerte replantearte tu 'tipo'?"},
 {'tema': 'ATRACCION', 'nivel': '💣 BOMBA', 'pregunta': '¿Con quién crees que habría más tensión en una quedada?'},
 {'tema': 'ATRACCION', 'nivel': '🟡 SALSEO', 'pregunta': '¿Quién sería tu peor idea sentimental dentro del grupo?'},
 {'tema': 'ATRACCION',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Quién sería la persona más difícil de olvidar después de una noche?'},
 {'tema': 'ATRACCION', 'nivel': '💣 BOMBA', 'pregunta': '¿A quién te sorprendería descubrir que le gustas?'},
 {'tema': 'ATRACCION', 'nivel': '🟡 SALSEO', 'pregunta': '¿Quién crees que coquetea sin darse cuenta?'},
 {'tema': 'ATRACCION',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Con quién te costaría más mantener una relación puramente amistosa si hubiera química?'},
 {'tema': 'ATRACCION',
  'nivel': '💣 BOMBA',
  'pregunta': '¿Quién crees que podría gustarte más en persona que por Telegram?'},
 {'tema': 'ATRACCION', 'nivel': '🟡 SALSEO', 'pregunta': '¿Quién tiene la voz más atractiva del grupo?'},
 {'tema': 'ATRACCION', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién crees que sería mejor en una primera cita?'},
 {'tema': 'ATRACCION', 'nivel': '💣 BOMBA', 'pregunta': '¿Quién crees que sería peor pareja para ti?'},
 {'tema': 'ATRACCION', 'nivel': '🟡 SALSEO', 'pregunta': '¿Quién crees que sería mejor pareja para ti?'},
 {'tema': 'ATRACCION', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿A quién te daría más corte confesarle que te atrae?'},
 {'tema': 'ATRACCION', 'nivel': '💣 BOMBA', 'pregunta': '¿Quién podría ponerte nervioso/a simplemente mirándote?'},
 {'tema': 'ATRACCION',
  'nivel': '🟡 SALSEO',
  'pregunta': '¿Quién crees que tiene más facilidad para generar tensión sexual?'},
 {'tema': 'ATRACCION',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Con quién te meterías en un lío aun sabiendo que probablemente acabaría mal?'},
 {'tema': 'ATRACCION', 'nivel': '💣 BOMBA', 'pregunta': '¿Quién crees que sería más celoso/a en pareja?'},
 {'tema': 'ATRACCION', 'nivel': '🟡 SALSEO', 'pregunta': '¿Quién parece más cariñoso/a en pareja de lo que aparenta?'},
 {'tema': 'ATRACCION', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién parece más difícil de conquistar?'},
 {'tema': 'ATRACCION', 'nivel': '💣 BOMBA', 'pregunta': '¿Quién crees que se enamora más rápido?'},
 {'tema': 'ATRACCION', 'nivel': '🟡 SALSEO', 'pregunta': '¿Quién crees que huye antes cuando empieza a sentir algo?'},
 {'tema': 'ATRACCION', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién crees que tiene más miedo al compromiso?'},
 {'tema': 'ATRACCION',
  'nivel': '💣 BOMBA',
  'pregunta': '¿Quién crees que podría tener una historia secreta con alguien de aquí?'},
 {'tema': 'ATRACCION', 'nivel': '🟡 SALSEO', 'pregunta': '¿Entre qué dos personas notas más química?'},
 {'tema': 'ATRACCION', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Qué dos miembros pegarían más como pareja?'},
 {'tema': 'ATRACCION', 'nivel': '💣 BOMBA', 'pregunta': '¿Qué dos miembros serían un desastre absoluto como pareja?'},
 {'tema': 'ATRACCION',
  'nivel': '🟡 SALSEO',
  'pregunta': '¿A quién del grupo le aceptarías una cita sin pensarlo demasiado?'},
 {'tema': 'ATRACCION', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Con quién te daría más miedo acabar sintiendo algo?'},
 {'tema': 'ATRACCION',
  'nivel': '💣 BOMBA',
  'pregunta': '¿Quién podría hacerte caer aunque inicialmente dijeras que no?'},
 {'tema': 'ATRACCION', 'nivel': '🟡 SALSEO', 'pregunta': '¿Quién crees que besa mejor solo por la impresión que te da?'},
 {'tema': 'ATRACCION',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Quién crees que tiene más éxito ligando fuera del grupo?'},
 {'tema': 'ATRACCION',
  'nivel': '💣 BOMBA',
  'pregunta': '¿Quién crees que es más selectivo/a para acostarse con alguien?'},
 {'tema': 'ATRACCION', 'nivel': '🟡 SALSEO', 'pregunta': '¿Quién crees que se hace más el/la difícil cuando liga?'},
 {'tema': 'ATRACCION',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Quién podría hacer que rompieras alguna de tus reglas sentimentales?'},
 {'tema': 'ATRACCION',
  'nivel': '💣 BOMBA',
  'pregunta': '¿Con quién tendrías una aventura si no existieran consecuencias?'},
 {'tema': 'ATRACCION', 'nivel': '🟡 SALSEO', 'pregunta': '¿Quién te parece más atractivo/a cuanto más lo conoces?'},
 {'tema': 'ATRACCION',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿Quién te parecía más atractivo/a al principio que ahora?'},
 {'tema': 'ATRACCION', 'nivel': '💣 BOMBA', 'pregunta': '¿Quién crees que podría despertar más celos sin proponérselo?'},
 {'tema': 'ATRACCION', 'nivel': '🟡 SALSEO', 'pregunta': '¿A quién del grupo presentarías como tu pareja ficticia?'},
 {'tema': 'ATRACCION', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién sería más peligroso/a como ex?'},
 {'tema': 'ATRACCION', 'nivel': '💣 BOMBA', 'pregunta': '¿Quién crees que vuelve más veces con sus ex?'},
 {'tema': 'ATRACCION', 'nivel': '🟡 SALSEO', 'pregunta': '¿Quién crees que tiene más historias de ligue que no cuenta?'},
 {'tema': 'ATRACCION',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿A quién del grupo le darías un beso por una apuesta sin problema?'},
 {'tema': 'ATRACCION',
  'nivel': '💣 BOMBA',
  'pregunta': '¿Con quién te costaría más actuar con normalidad después de un beso?'},
 {'tema': 'ATRACCION',
  'nivel': '🟡 SALSEO',
  'pregunta': '¿Quién crees que sería más intenso/a después de acostarse con alguien?'},
 {'tema': 'ATRACCION', 'nivel': '🔴 SIN FILTRO', 'pregunta': '¿Quién crees que separa mejor sexo y sentimientos?'},
 {'tema': 'ATRACCION', 'nivel': '💣 BOMBA', 'pregunta': '¿Quién crees que los mezcla inevitablemente?'},
 {'tema': 'ATRACCION',
  'nivel': '🟡 SALSEO',
  'pregunta': '¿Quién crees que podría enamorarse de alguien del grupo sin decir nada?'},
 {'tema': 'ATRACCION',
  'nivel': '🔴 SIN FILTRO',
  'pregunta': '¿A quién te gustaría saber si alguna vez se ha fijado en ti?'},
 {'tema': 'ATRACCION',
  'nivel': '💣 BOMBA',
  'pregunta': '¿Quién crees que tiene más posibilidades de acabar liándose con alguien del grupo?'}]

def _elegir_pregunta(context):
    usadas = context.chat_data.setdefault("dadonet_usadas_v2", [])
    temas_recientes = context.chat_data.setdefault("dadonet_temas_recientes_v2", [])

    disponibles = [x for x in PREGUNTAS if x["pregunta"] not in usadas]
    if not disponibles:
        usadas.clear()
        disponibles = PREGUNTAS[:]

    variadas = [x for x in disponibles if x["tema"] not in temas_recientes[-3:]]
    if variadas:
        disponibles = variadas

    elegida = random.choice(disponibles)
    usadas.append(elegida["pregunta"])
    temas_recientes.append(elegida["tema"])
    if len(temas_recientes) > 3:
        del temas_recientes[:-3]

    return elegida

async def dadonet(update, context):
    elegida = _elegir_pregunta(context)
    texto = (
        f"🎲 DADONET\n\n"
        f"{elegida['nivel']}\n\n"
        f"{elegida['pregunta']}\n\n"
        f"🎲 1–3 → Elige quién responde 😈\n"
        f"🎲 4–6 → Te toca responder a ti ☠️"
    )
    await update.message.reply_text(texto)
