import random

SALSEO = ['¿Quién del grupo te cayó mejor desde el primer día?',
 '¿Quién del grupo te cayó peor al principio y ahora te cae mejor?',
 '¿Quién te cayó bien al principio y ahora te genera más dudas?',
 '¿Quién del grupo crees que habla por privado con más gente de la que reconoce?',
 '¿Quién crees que se hace más el inocente de lo que realmente es?',
 '¿Quién del grupo te genera más curiosidad aunque apenas hayas hablado con esa persona?',
 '¿Con quién del grupo crees que tendrías una conversación de horas sin aburrirte?',
 '¿Quién del grupo crees que podría sorprenderte muchísimo en persona?',
 '¿Quién crees que tiene una personalidad muy distinta por privado que en el grupo?',
 '¿Quién del grupo crees que sabe más salseos de los que cuenta?',
 '¿Quién crees que observa mucho más de lo que participa?',
 '¿Quién del grupo crees que tiene más facilidad para ligar sin proponérselo?',
 '¿Quién crees que tiene más gente detrás de lo que aparenta?',
 '¿Quién del grupo sería tu compañero/a perfecto/a para una noche de fiesta?',
 '¿Con quién del grupo te irías de viaje un fin de semana sin conocerlo mucho más?',
 '¿Quién crees que sería capaz de desaparecer del grupo y volver un mes después como si nada?',
 '¿Quién del grupo crees que se mete en más líos sentimentales?',
 '¿Quién crees que podría acabar emparejado con alguien del grupo?',
 '¿Quién del grupo crees que tiene más paciencia para aguantar dramas?',
 '¿Quién sería la peor persona para confiarle un secreto pequeño?',
 '¿Quién del grupo te parece más difícil de conocer de verdad?',
 '¿Quién crees que tiene más doble vida entre lo que cuenta aquí y su vida real?',
 '¿Quién del grupo crees que es más celoso/a de lo que reconoce?',
 '¿Quién crees que se engancha emocionalmente más rápido?',
 '¿Quién del grupo crees que tarda menos en cansarse de alguien?',
 '¿Quién crees que tiene más posibilidades de enamorarse de alguien del grupo?',
 '¿Quién del grupo crees que podría tener una relación secreta y nadie se enteraría?',
 '¿Quién te parece más probable que haya cotilleado el perfil entero de alguien del grupo?',
 '¿Quién crees que borra mensajes después de mandarlos porque se arrepiente?',
 "¿Quién del grupo sería capaz de montar una película mental por un simple 'visto'?",
 '¿Quién crees que más disimula cuando alguien le gusta?',
 '¿Quién del grupo crees que se pica más cuando le llevan la contraria?',
 '¿Quién crees que tendría más éxito organizando una quedada del grupo?',
 '¿Quién del grupo crees que sería más divertido/a de conocer cara a cara?',
 '¿Quién crees que podría acabar siendo tu mejor amigo/a de aquí?',
 '¿A quién del grupo le preguntarías primero si quisieras enterarte de un salseo?',
 '¿Quién crees que se da cuenta antes que nadie de quién está tonteando con quién?',
 '¿Quién del grupo crees que podría guardar un secreto durante años?',
 '¿Quién del grupo te parece más imprevisible?',
 '¿Quién crees que podría caerle bien a casi todo el mundo en persona?',
 '¿Quién del grupo te parece que da una imagen más dura de lo que realmente es?',
 '¿Quién crees que aparenta ser más tranquilo/a de lo que es?',
 '¿Quién del grupo te parece que podría tener más anécdotas que todavía no ha contado?',
 '¿Quién crees que escucha más audios ajenos con cara de detective?',
 '¿Quién del grupo te parece más probable que tenga capturas guardadas?',
 '¿Quién crees que es más de enterarse de algo y hacerse el loco/a?',
 '¿Quién del grupo te parece que podría enamorarse de una voz?',
 '¿Quién crees que se fijaría primero en alguien nuevo que entra al grupo?',
 '¿Quién del grupo podría hacer amistad con cualquiera en cinco minutos?',
 '¿Quién crees que sería el más cotilla en una quedada?',
 '¿Quién del grupo tiene más pinta de recordar absolutamente todo lo que se dice?',
 '¿Quién crees que podría ser el primero en darse cuenta de una mentira?',
 '¿Quién del grupo parece más fácil de picar?',
 '¿Quién crees que se toma mejor las bromas y quién peor?',
 '¿Quién del grupo parece tener más paciencia con la gente intensa?',
 '¿Quién crees que sería el primero en meterse en un debate innecesario?',
 '¿Quién del grupo tiene más pinta de cambiar totalmente tu opinión al conocerlo en persona?',
 '¿Quién crees que es más de hablar mucho por privado y poco en el grupo?',
 '¿Quién del grupo parece más probable que se encariñe con alguien sin querer?',
 '¿Quién crees que tendría más posibilidades de caer bien a tu círculo de amigos?',
 '¿Quién del grupo parece tener más historias de ex que contar?',
 '¿Quién crees que sería el primero en enterarse de un lío sentimental dentro del grupo?',
 "¿Quién del grupo te parece más probable que diga 'me da igual' cuando claramente no le da igual?",
 '¿Quién crees que se enamoraría de alguien que no le conviene?',
 "¿Quién del grupo tiene más pinta de haber dicho 'yo nunca haría eso' y luego hacerlo?",
 '¿Quién crees que sería el más divertido/a en un viaje de grupo?',
 '¿Quién te parece más probable que tenga una opinión secreta sobre casi todos?',
 '¿Quién del grupo parece que podría caer mal sin querer por su forma de escribir?',
 '¿Quién crees que sería el primero en pedir perdón después de una discusión?',
 '¿Quién del grupo sería más difícil de olvidar después de conocerlo?',
 '¿Quién crees que podría tener más admiradores silenciosos?',
 '¿Quién del grupo parece que daría el mejor consejo sentimental?',
 '¿Quién crees que daría el peor consejo sentimental pero con muchísima seguridad?',
 '¿Quién del grupo parece más probable que reaparezca en la vida de un ex?',
 '¿Quién crees que tiene más facilidad para detectar cuando alguien está mintiendo?',
 '¿Quién del grupo parece más probable que se enamore por cómo le tratan y no por el físico?',
 '¿Quién crees que podría liarla más en una quedada sin proponérselo?',
 '¿Quién del grupo parece tener más carácter del que muestra?',
 '¿Quién crees que puede ser mucho más tímido/a en persona de lo que parece aquí?',
 '¿Quién del grupo parece que se guardaría algo importante para evitar drama?']

SIN_FILTRO = ['¿Quién del grupo te atrae más físicamente?',
 '¿A quién del grupo besarías si tuvieras que elegir ahora mismo?',
 '¿Con quién del grupo crees que tendrías más química en persona?',
 '¿Con quién del grupo tendrías una cita solo por curiosidad?',
 '¿Quién del grupo te parece más peligroso/a sentimentalmente?',
 '¿Quién crees que sería peor pareja?',
 '¿Quién crees que sería mejor pareja?',
 '¿Quién del grupo crees que rompería más corazones?',
 '¿Con quién del grupo jamás tendrías nada aunque te lo pusieran facilísimo?',
 '¿Quién crees que está más bueno/a de lo que enseñan sus fotos?',
 '¿Quién del grupo te genera más curiosidad sexual?',
 '¿Quién crees que sería mejor amante?',
 '¿Quién crees que sería peor amante?',
 '¿Con quién del grupo te liarías una noche sabiendo que al día siguiente no pasaría nada?',
 '¿Con quién del grupo no te importaría que surgiera algo inesperado?',
 '¿Quién del grupo crees que podría hacerte perder la cabeza?',
 '¿A quién del grupo bloquearías durante 24 horas solo por tocar los cojones?',
 '¿Quién del grupo te parece más probable que se haya fijado en alguien y no lo reconozca?',
 '¿Quién crees que está tonteando con alguien del grupo aunque diga que no?',
 '¿A quién del grupo le darías una oportunidad si te pidiera una cita?',
 '¿Quién del grupo te parece más probable que tenga un crush secreto?',
 '¿Quién crees que tendría más posibilidades contigo si se lo propusiera?',
 '¿Quién del grupo te parece más probable que ligue por mensaje privado?',
 '¿Quién crees que puede ser más intenso/a cuando le gusta alguien?',
 '¿Quién del grupo crees que se enamora peor?',
 '¿Quién crees que tarda menos en sustituir a una persona cuando una relación termina?',
 '¿Quién del grupo crees que volvería con un ex aunque jurara que jamás lo haría?',
 '¿Quién te parece más probable que haya enviado un mensaje borracho/a y se arrepintiera al día siguiente?',
 '¿Quién crees que sería capaz de tener dos conversaciones románticas abiertas al mismo tiempo?',
 '¿Quién del grupo crees que tiene más posibilidades de estar hablando con alguien del grupo por privado ahora mismo?',
 '¿A quién del grupo te costaría más decirle que no si se lanzara contigo?',
 '¿Quién del grupo te parece más atractivo/a por personalidad que por físico?',
 '¿Quién del grupo te parece más atractivo/a físicamente que por personalidad?',
 '¿Quién crees que podría gustarte mucho más después de conocerlo en persona?',
 '¿Quién crees que podría decepcionarte más al conocerlo en persona?',
 '¿Quién del grupo crees que tiene más posibilidades de ser tóxico/a en pareja?',
 '¿Quién crees que sería más posesivo/a?',
 '¿Quién crees que llevaría peor que su pareja tuviera mucha relación con otras personas del grupo?',
 '¿Quién crees que sería capaz de mirar el móvil de su pareja?',
 '¿Quién del grupo crees que perdonaría una infidelidad?',
 '¿Quién crees que jamás perdonaría una infidelidad?',
 '¿Quién del grupo crees que podría ser infiel y conseguir que nadie se enterara?',
 '¿Quién del grupo crees que tiene más secretos sentimentales?',
 '¿Con quién del grupo tendrías más miedo de engancharte emocionalmente?',
 '¿A quién del grupo te gustaría conocer mejor aunque nunca se lo hayas dicho?',
 '¿Quién del grupo te ha sorprendido para bien últimamente?',
 '¿Quién del grupo te ha decepcionado un poco últimamente?',
 '¿Quién crees que tiene una opinión sobre ti que nunca se atrevería a decirte?',
 '¿De quién del grupo te gustaría saber qué piensa realmente de ti?',
 '¿Quién crees que te juzgó mal cuando entraste al grupo?',
 '¿Quién del grupo crees que te conoce menos de lo que piensa?',
 '¿Quién del grupo crees que sabe exactamente cómo picarte?',
 '¿Quién podría hacerte enfadar más rápido?',
 '¿Con quién del grupo sería más probable que acabaras discutiendo y reconciliándote el mismo día?',
 '¿Quién crees que sería capaz de hacerse el/la duro/a y luego pillarse muchísimo?',
 '¿Quién del grupo crees que tiene más miedo al compromiso?',
 '¿Quién crees que tendría una relación más caótica?',
 '¿Quién del grupo crees que sería el primero en tener algo con otra persona del grupo?',
 '¿Quién te parece que está más acostumbrado/a a salirse con la suya?',
 '¿Quién del grupo crees que tiene más facilidad para manipular una situación a su favor?',
 '¿Quién crees que sería capaz de negar hasta la muerte que alguien le gusta aunque fuera evidente?',
 '¿Quién del grupo te parece más probable que se obsesione con alguien que le da atención intermitente?',
 '¿Quién crees que tiene más posibilidades de liarse con alguien en una quedada?',
 '¿A quién del grupo besarías solo por comprobar si hay química?',
 '¿Quién te parece más probable que tenga una relación de amor-odio con alguien del grupo?',
 '¿Quién del grupo crees que podría hacer ghosting después de una noche intensa?',
 '¿Quién crees que sería capaz de volver a escribir a alguien solo porque lo vio feliz sin él/ella?',
 '¿Quién del grupo te parece más probable que tenga celos sin tener derecho a tenerlos?',
 '¿A quién del grupo te costaría más ver con otra persona?',
 '¿Quién crees que podría confundirte más emocionalmente?',
 '¿Quién del grupo crees que podría gustarte aunque no encaje nada con tu tipo habitual?',
 '¿Quién te parece más probable que se enganche después de decir que solo quiere algo casual?',
 '¿Quién del grupo crees que ha tenido más líos de los que cuenta?',
 '¿Quién crees que sabe exactamente cómo seducir cuando quiere?',
 '¿Quién del grupo te parece más probable que termine pillándose de alguien prohibido?',
 '¿A quién del grupo te daría curiosidad besar aunque no tuvieras intención de nada más?',
 '¿Quién crees que podría tener más química contigo pero también darte más problemas?',
 '¿Quién del grupo sería más difícil de rechazar si se pusiera serio/a contigo?',
 '¿Quién crees que podría ponerse celoso/a sin admitirlo?',
 '¿Quién del grupo te parece más probable que haya fantaseado con alguien de aquí?']

BOMBA = ['Si tuvieras que acostarte con una persona del grupo, ¿a quién elegirías?',
 'Si tuvieras que besar a dos personas del grupo esta noche, ¿quiénes serían?',
 '¿Con quién del grupo tendrías sexo y con quién jamás aunque fueras la última persona del planeta?',
 '¿Quién del grupo crees que te atraería más si lo tuvieras delante ahora mismo?',
 'Si mañana despertaras en la cama con alguien del grupo, ¿con quién preferirías que fuera?',
 "¿A quién del grupo mandarías un mensaje de 'ven' a las tres de la mañana?",
 '¿Quién del grupo crees que tendría más posibilidades de hacerte ser infiel?',
 '¿Con quién del grupo tendrías una aventura que nadie pudiera descubrir?',
 '¿Quién del grupo crees que podría hacerte olvidar a alguien que todavía te importa?',
 '¿A quién del grupo le aceptarías una proposición indecente sin pensarlo demasiado?',
 'Si tuvieras que elegir pareja dentro del grupo durante un año entero, ¿a quién elegirías?',
 '¿A quién del grupo elegirías para una noche y a quién para una relación?',
 '¿Quién del grupo te parece demasiado atractivo/a como para ser buena idea?',
 '¿Quién crees que podría acabar siendo tu peor decisión sentimental?',
 '¿Con quién del grupo crees que habría más tensión sexual si os vierais en persona?',
 'Si pudieras leer un solo chat privado de alguien del grupo, ¿de quién sería?',
 '¿A quién del grupo jamás le dejarías leer tus conversaciones privadas?',
 'Si supieras que alguien del grupo está pillado por ti, ¿quién te gustaría que fuera?',
 '¿Quién del grupo te dolería más descubrir que habla mal de ti por privado?',
 '¿A quién del grupo eliminarías definitivamente si tuvieras que elegir a una persona?',
 '¿Quién del grupo crees que esconde la opinión más fuerte sobre otra persona del grupo?',
 'Di una persona del grupo con la que tendrías algo y una con la que ni de coña.',
 '¿Quién del grupo crees que tiene más posibilidades de acabar teniendo sexo con otra persona del grupo?',
 "¿Quién del grupo sería tu elección si te dijeran: 'o te lías con esta persona o abandonas el grupo'?",
 'Si esta noche hubiera una fiesta privada solo con gente del grupo, ¿con quién crees que acabarías tonteando?',
 'Si tuvieras que mandar una foto provocativa a alguien del grupo, ¿a quién sería?',
 '¿Con quién del grupo aceptarías compartir habitación en una escapada sabiendo que solo hay una cama?',
 'Si tuvieras que elegir a alguien del grupo para darte un beso de diez segundos, ¿quién sería?',
 '¿A quién del grupo besarías aunque supieras que luego se iba a montar un drama enorme?',
 '¿Con quién del grupo crees que tendrías más riesgo de engancharte después de una sola noche?',
 '¿Quién del grupo crees que podría romperte el corazón de verdad?',
 '¿A quién del grupo llamarías si estuvieras emocionalmente débil y quisieras cometer una mala decisión?',
 '¿Quién crees que podría hacerte traicionar una regla que juraste no romper?',
 '¿Con quién del grupo te meterías en un lío aunque supieras que acabaría mal?',
 '¿Quién del grupo te pondría más nervioso/a si te confesara que le gustas?',
 'Si tuvieras que tener una cita secreta con alguien del grupo, ¿a quién elegirías?',
 '¿Quién del grupo crees que podría acabar gustándote demasiado si empezaras a hablar mucho por privado?',
 '¿Quién te parece la persona del grupo con más posibilidades de ser tu debilidad?',
 '¿A quién del grupo no deberías besar porque sabes que te complicaría la vida?',
 '¿Con quién del grupo crees que sería más difícil mantenerlo solo en algo físico?',
 'Si solo pudieras hablar por privado con una persona del grupo durante un mes, ¿a quién elegirías?',
 '¿A quién del grupo le confiarías una confesión que podría cambiar la opinión que tiene de ti?',
 '¿Quién del grupo crees que podría hacerte sentir celos aunque no fuerais nada?',
 'Si tuvieras que borrar para siempre a una persona del grupo y acercarte mucho más a otra, ¿quiénes serían?',
 '¿Quién del grupo crees que tiene más posibilidades de haber mentido sobre quién le gusta?',
 '¿Quién del grupo crees que podría estar sintiendo algo por alguien y fingiendo que no?',
 '¿A quién del grupo te daría más vergüenza admitir que te atrae?',
 '¿Con quién del grupo tendrías una cita aunque supieras que alguien se iba a enfadar?',
 '¿Quién del grupo crees que podría hacerte caer en una relación que sabes que no te conviene?',
 '¿A quién del grupo elegirías para un beso, a quién para una noche y a quién para una relación?',
 '¿Quién del grupo sería tu mayor tentación si estuvieras soltero/a y todos estuvieran disponibles?',
 "¿A quién del grupo te gustaría escuchar decirte claramente 'me gustas'?",
 '¿Quién crees que tendría más poder sobre ti si empezaras a sentir algo?',
 '¿A quién del grupo besarías delante de todos solo por ver qué pasa?',
 'Si tuvieras que elegir a alguien del grupo para una noche sin consecuencias, ¿quién sería?',
 '¿Quién del grupo crees que podría hacerte actuar de una forma que normalmente no harías?',
 '¿A quién del grupo te dolería más ver enamorándose de otra persona?',
 '¿Quién del grupo crees que podría convertirse en tu problema favorito?',
 'Si tuvieras que confesar una atracción por alguien del grupo ahora mismo, ¿a quién nombrarías?',
 '¿Quién del grupo crees que sería la peor persona de la que podrías enamorarte?',
 '¿Con quién del grupo aceptarías una escapada de 48 horas sin contarle a nadie dónde vais?',
 '¿A quién del grupo dejarías acercarse demasiado sabiendo que probablemente acabarías pillándote?',
 "¿Quién del grupo crees que podría hacerte romper tu propio 'tipo' completamente?",
 'Si pudieras saber quién ha fantaseado contigo dentro del grupo, ¿de quién te gustaría descubrirlo?',
 '¿Con quién del grupo crees que habría más posibilidades de acabar haciendo algo que luego negaríais?',
 "¿A quién del grupo le mandarías un '¿estás despierto/a?' sabiendo exactamente lo que significa?",
 '¿Quién del grupo crees que sería capaz de hacerte sentir mariposas y ansiedad al mismo tiempo?',
 '¿A quién del grupo elegirías si tuvieras que pasar una noche entera hablando a solas, sin móviles ni escapatoria?',
 '¿Quién del grupo crees que sería la persona más peligrosa para ti si hubiera atracción mutua?',
 '¿A quién del grupo no invitarías jamás a conocer a tu pareja por miedo a que hubiera química?',
 'Si tuvieras que admitir que alguien del grupo te parece irresistible, ¿quién sería?',
 '¿Quién del grupo crees que podría hacerte caer aunque al principio no te gustara nada?',
 "¿A quién del grupo te costaría más decirle 'esto no puede seguir'?",
 '¿Quién del grupo crees que podría hacerte olvidar una promesa que te hiciste a ti mismo/a?',
 '¿Con quién del grupo crees que una amistad tendría más riesgo de convertirse en otra cosa?',
 '¿Quién del grupo te parece más probable que termine siendo un secreto que no contarías a nadie?',
 'Si tuvieras que elegir a una persona para que te bese y otra para que te rechace, ¿quiénes serían?',
 '¿Quién del grupo crees que podría sacar tu lado más celoso/a?',
 '¿A quién del grupo le permitirías acercarse a ti aunque supieras que es una pésima idea?',
 '¿Quién del grupo sería la persona que más te costaría sacar de tu cabeza después de una noche juntos?']

CATEGORIAS = {
    "🟡 SALSEO": SALSEO,
    "🔴 SIN FILTRO": SIN_FILTRO,
    "💣 BOMBA": BOMBA,
}

PESOS = {
    "🟡 SALSEO": 30,
    "🔴 SIN FILTRO": 45,
    "💣 BOMBA": 25,
}

def _elegir_categoria():
    categorias = list(CATEGORIAS.keys())
    pesos = [PESOS[c] for c in categorias]
    return random.choices(categorias, weights=pesos, k=1)[0]

def _elegir_pregunta(context):
    """
    No repite preguntas hasta agotar todas las de esa categoría.
    Cada chat mantiene su propio historial mientras el bot está encendido.
    """
    categoria = _elegir_categoria()

    usadas_por_categoria = context.chat_data.setdefault(
        "dadonet_usadas",
        {nombre: [] for nombre in CATEGORIAS}
    )

    usadas = usadas_por_categoria.setdefault(categoria, [])
    disponibles = [p for p in CATEGORIAS[categoria] if p not in usadas]

    # Solo cuando ya han salido TODAS las preguntas de esa categoría,
    # se vacía el historial y comienza un ciclo nuevo.
    if not disponibles:
        usadas.clear()
        disponibles = CATEGORIAS[categoria][:]

    pregunta = random.choice(disponibles)
    usadas.append(pregunta)

    return categoria, pregunta

async def dadonet(update, context):
    categoria, pregunta = _elegir_pregunta(context)

    texto = (
        f"🎲 DADONET\n\n"
        f"{categoria}\n\n"
        f"{pregunta}\n\n"
        f"🎲 1–3 → Elige quién responde 😈\n"
        f"🎲 4–6 → Te toca responder a ti ☠️"
    )

    await update.message.reply_text(texto)
