# Banco de misiones para "El juego de los secretos" de No es Tinderbot.
# Todas están pensadas para poder intentarse dentro de una conversación normal.

MISIONES_SECRETOS = [
    "Consigue que alguien diga «red flag».",
    "Consigue que alguien te pregunte «¿por qué?».",
    "Haz que alguien diga «literal».",
    "Consigue que alguien use el emoji 😂 en respuesta a algo tuyo.",
    "Haz que alguien te diga que estás exagerando.",
    "Consigue que alguien mencione a un ex sin preguntarle directamente por un ex.",
    "Haz que alguien diga que tiene hambre.",
    "Consigue que alguien recomiende una serie.",
    "Haz que alguien recomiende una película.",
    "Consigue que alguien hable de comida sin que tú nombres ningún plato.",
    "Haz que alguien diga «depende».",
    "Consigue que alguien escriba tu nombre en el chat.",
    "Haz que dos personas diferentes te lleven la contraria.",
    "Consigue que alguien te pregunte si estás bien.",
    "Haz que alguien diga «qué fuerte».",
    "Consigue que alguien diga que no está de acuerdo contigo.",
    "Haz que alguien cambie de opinión durante una conversación.",
    "Consigue que alguien cuente una anécdota de su infancia.",
    "Haz que alguien hable de su trabajo.",
    "Consigue que alguien mencione el café.",
    "Haz que alguien diga que está cansado/a.",
    "Consigue que alguien hable de dormir o de sueño.",
    "Haz que alguien mencione una canción.",
    "Consigue que alguien mande un GIF.",
    "Haz que alguien mande un sticker después de un mensaje tuyo.",
    "Consigue que alguien responda a uno de tus mensajes con una sola palabra.",
    "Haz que alguien te haga dos preguntas seguidas.",
    "Consigue que alguien te pregunte de dónde eres.",
    "Haz que alguien cuente cuál fue su última compra.",
    "Consigue que alguien hable de viajar.",
    "Haz que alguien nombre una ciudad española.",
    "Consigue que alguien hable del tiempo o del clima.",
    "Haz que alguien diga que algo le da vergüenza.",
    "Consigue que alguien confiese una manía.",
    "Haz que alguien diga «yo nunca».",
    "Consigue que alguien cuente algo que le dé miedo.",
    "Haz que alguien diga «ni de coña».",
    "Consigue que alguien use tres emojis en un mismo mensaje.",
    "Haz que alguien te responda con un audio.",
    "Consigue que alguien diga que se aburre.",
    "Haz que alguien mencione TikTok.",
    "Consigue que alguien mencione Instagram.",
    "Haz que alguien mencione otra app distinta de Telegram.",
    "Consigue que alguien diga que algo es «cringe».",
    "Haz que alguien utilice la palabra «random».",
    "Consigue que alguien diga «bro» o una variante, aunque esté prohibido y sea de broma.",
    "Haz que alguien diga que no sabe qué responder.",
    "Consigue que alguien te acuse de estar tramando algo.",
    "Haz que alguien sospeche públicamente de ti.",
    "Consigue que alguien diga «te conozco» o «ya te conozco».",
    "Haz que alguien diga que una persona del grupo tiene mucho cuento.",
    "Consigue que alguien etiquete a otra persona del grupo por culpa de algo que tú has dicho.",
    "Haz que alguien defienda una comida que otra persona critique.",
    "Consigue que empiece un pequeño debate sobre comida.",
    "Haz que alguien diga que la pizza con piña está bien o mal.",
    "Consigue que alguien hable de su desayuno.",
    "Haz que alguien diga cuál es su comida favorita.",
    "Consigue que alguien mencione una bebida alcohólica sin pedírselo directamente.",
    "Haz que alguien diga que necesita vacaciones.",
    "Consigue que alguien diga dónde le gustaría viajar.",
    "Haz que alguien mencione un país al que no iría.",
    "Consigue que alguien diga que odia los lunes.",
    "Haz que alguien celebre que es viernes o fin de semana.",
    "Consigue que alguien diga qué hora se suele dormir.",
    "Haz que alguien admita que mira el móvil nada más despertarse.",
    "Consigue que alguien diga que tiene demasiados chats sin responder.",
    "Haz que alguien cuente una excusa que haya usado alguna vez.",
    "Consigue que alguien admita haber llegado tarde a algo importante.",
    "Haz que alguien diga que se ha perdido usando GPS o Maps.",
    "Consigue que alguien cuente una compra absurda.",
    "Haz que alguien diga que se arrepiente de haber enviado un mensaje alguna vez.",
    "Consigue que alguien hable de una cita desastrosa.",
    "Haz que alguien diga qué cosa le hace perder interés en una persona.",
    "Consigue que alguien mencione una red flag propia.",
    "Haz que alguien diga qué red flag no soporta.",
    "Consigue que alguien diga que ha ghosteado o que le han ghosteado.",
    "Haz que alguien defienda que responder rápido no significa nada.",
    "Consigue que alguien diga si cree en segundas oportunidades.",
    "Haz que alguien hable de celos sin preguntarle directamente si es celoso/a.",
    "Consigue que alguien diga que no se enamora fácilmente.",
    "Haz que alguien admita que sobrepiensa los mensajes.",
    "Consigue que alguien diga qué le atrae primero de una persona.",
    "Haz que alguien diga que se ha enamorado de una voz o podría hacerlo.",
    "Consigue que alguien hable de una amistad que empezó por internet.",
    "Haz que alguien diga si conocería en persona a alguien del grupo.",
    "Consigue que alguien diga quién del grupo parece más misterioso/a.",
    "Haz que alguien nombre a la persona del grupo que cree que tiene más cotilleos.",
    "Consigue que alguien diga quién sobreviviría mejor a un apocalipsis.",
    "Haz que alguien diga quién del grupo llegaría tarde a su propia boda.",
    "Consigue que alguien señale quién manda más audios largos.",
    "Haz que alguien diga quién parece tener más paciencia.",
    "Consigue que alguien diga quién parece más cabezota.",
    "Haz que alguien diga quién parece más dramático/a.",
    "Consigue que alguien diga quién parece más probable que desaparezca una semana.",
    "Haz que alguien diga quién parece más probable que se haga viral.",
    "Consigue que alguien diga quién sería peor compañero/a de piso.",
    "Haz que alguien diga quién sería mejor compañero/a de viaje.",
    "Consigue que alguien diga quién parece más competitivo/a.",
    "Haz que alguien diga quién parece más cotilla.",
    "Consigue que alguien diga quién parece más inocente de lo que realmente es.",
    "Haz que alguien diga quién parece tener más historias que no cuenta.",
    "Consigue que alguien diga «esto parece Tinder» o haga una broma con Tinder.",
    "Haz que alguien diga que este grupo es un caos.",
    "Consigue que alguien diga que aquí hay demasiado salseo.",
    "Haz que alguien diga que el grupo está muerto o demasiado tranquilo.",
    "Consigue que alguien pida que se haga un juego.",
    "Haz que alguien mencione el Trivial del grupo.",
    "Consigue que alguien mencione el Tribunal del grupo.",
    "Haz que alguien mencione DadoNet.",
    "Consigue que alguien diga que No es Tinderbot da miedo o sabe demasiado.",
    "Haz que alguien pregunte qué está haciendo el bot.",
    "Consigue que alguien diga que quiere ganar.",
    "Haz que alguien te diga «tramposo/a» aunque sea de broma.",
    "Consigue que alguien diga que no se fía de ti.",
    "Haz que alguien diga «te has delatado».",
    "Consigue que alguien diga «eso es muy sospechoso».",
    "Haz que alguien cambie de tema después de un mensaje tuyo.",
    "Consigue que dos personas empiecen a hablar entre ellas a partir de una pregunta tuya.",
    "Haz que una persona que llevaba un rato sin hablar participe en la conversación.",
    "Consigue que alguien responda a una pregunta tuya y luego te haga otra.",
    "Haz que alguien te corrija un dato o una opinión.",
    "Consigue que alguien te dé la razón públicamente.",
    "Haz que alguien diga «exacto» o «tal cual».",
    "Consigue que alguien diga «es verdad».",
    "Haz que alguien escriba «JAJA» en mayúsculas.",
    "Consigue que alguien utilice un emoji de corazón.",
    "Haz que alguien utilice el emoji 👀.",
    "Consigue que alguien utilice el emoji 💀.",
    "Haz que alguien utilice el emoji 😭.",
    "Consigue que alguien mande una foto al grupo.",
    "Haz que alguien pregunte por una foto o imagen que se haya enviado.",
    "Consigue que alguien diga que algo le recuerda a otra persona del grupo.",
    "Haz que alguien cuente algo que le pasó hoy.",
    "Consigue que alguien diga cuál ha sido lo mejor de su día.",
    "Haz que alguien diga cuál ha sido lo peor de su día.",
    "Consigue que alguien mencione qué cenará o qué ha cenado.",
    "Haz que alguien hable de cocinar.",
    "Consigue que alguien diga si sabe cocinar bien o mal.",
    "Haz que alguien recomiende un restaurante, bar o sitio para comer.",
    "Consigue que alguien hable de mascotas.",
    "Haz que alguien diga qué animal tendría si pudiera.",
    "Consigue que alguien mencione un perro o un gato.",
    "Haz que alguien diga una opinión impopular.",
    "Consigue que alguien escriba «no me juzguéis» o algo equivalente.",
    "Haz que alguien admita un gusto que le dé un poco de vergüenza.",
    "Consigue que alguien diga una canción que le guste mucho.",
    "Haz que alguien mencione una película que haya visto más de una vez.",
    "Consigue que alguien diga una serie que abandonó a mitad.",
    "Haz que alguien diga qué personaje ficticio le cae fatal.",
    "Consigue que alguien cuente una teoría absurda que tenga.",
    "Haz que alguien diga qué haría si ganara mucho dinero mañana.",
    "Consigue que alguien diga en qué gastaría 1.000 euros inesperados.",
    "Haz que alguien diga si preferiría playa o montaña.",
    "Consigue que alguien elija entre salir de fiesta o plan tranquilo.",
    "Haz que alguien diga si es más de mañana o de noche.",
    "Consigue que alguien diga si prefiere llamadas o mensajes.",
    "Haz que alguien diga si odia o ama los audios largos.",
    "Consigue que alguien diga qué aplicación borraría para siempre.",
    "Haz que alguien admita cuánto tiempo puede perder viendo reels o vídeos cortos.",
    "Consigue que alguien diga una palabra que le dé manía.",
    "Haz que alguien diga una frase típica que usa demasiado.",
    "Consigue que alguien escriba un refrán o dicho popular.",
    "Haz que alguien recuerde una situación vergonzosa.",
    "Consigue que alguien cuente una mentira absurda que dijo para salir de un apuro.",
    "Haz que alguien admita una habilidad completamente inútil.",
    "Consigue que alguien diga algo que sabe hacer mejor de lo que parece.",
    "Haz que alguien diga qué superpoder elegiría.",
    "Consigue que alguien diga qué haría durante un apocalipsis.",
    "Haz que alguien diga qué tres cosas se llevaría a una isla desierta.",
    "Consigue que alguien diga cuál sería su trabajo ideal si el dinero no importara.",
    "Haz que alguien diga en qué país viviría durante un año.",
    "Consigue que alguien diga qué edad le gustaría volver a tener por un día.",
    "Haz que alguien diga qué década le habría gustado vivir.",
    "Consigue que alguien diga una cosa que jamás prestaría.",
    "Haz que alguien diga qué objeto pierde continuamente.",
    "Consigue que alguien admita que habla solo/a.",
    "Haz que alguien diga una costumbre rara que tenga cuando está solo/a.",
    "Consigue que alguien te responda «¿qué?» o «cómo?».",
    "Haz que alguien te pida que expliques mejor algo.",
    "Consigue que alguien diga que no te cree.",
    "Haz que alguien diga «puede ser».",
    "Consigue que alguien diga «no tengo pruebas pero tampoco dudas».",
    "Haz que alguien escriba una respuesta de cinco palabras o menos a una pregunta tuya.",
    "Consigue que alguien escriba un mensaje de más de tres líneas por algo que tú has preguntado.",
    "Haz que alguien cite o responda directamente a un mensaje tuyo.",
    "Consigue que alguien se ría de una broma tuya.",
    "Haz que alguien te pida una opinión.",
    "Consigue que alguien te pida consejo sobre algo.",
    "Haz que alguien diga «yo haría...» para aconsejar a otra persona.",
    "Consigue que alguien defienda a otra persona del grupo en una discusión amistosa.",
    "Haz que alguien diga que dos personas del grupo se parecen en algo.",
    "Consigue que alguien diga quién cree que sería mejor detective.",
    "Haz que alguien diga quién cree que mentiría mejor.",
    "Consigue que alguien diga quién sería peor guardando un secreto.",
    "Haz que alguien diga quién parece más difícil de engañar.",
    "Consigue que alguien diga quién parece más fácil de picar.",
]
